### ISSUE TITLE
Search Tab tooltip is constantly present

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#101]
The tooltip never disapear. 
![1](https://cloud.githubusercontent.com/assets/7251658/4456180/ad883bce-4887-11e4-9556-bb7a01d71480.JPG)

**Comment by simon-sh** [comment]
Problems to fix:

1) Get rid of this "tooltip" thing
    Why: tooltip visible when more then 2 airports selected - which is not likely to happend

2) Fix translation for ddl when more then 1 values selected. Current value: "%d ספקים נבחרו"
   Should be: "%d שדות תעופה"

![1](https://cloud.githubusercontent.com/assets/8789505/4472048/873e3aac-4942-11e4-9c9c-57bb8e0115e4.PNG)

**Comment by AlexSin15** [comment]
Changeset 2371
