### ISSUE TITLE
Search Flights-counting selected fields does not work correctly

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#107]
1. I have chosen from the list 2 airport-It write  selected 2 airport
2. then chose one of the fields in the pannel search airport It added to the amount of the selected airport

![1](https://cloud.githubusercontent.com/assets/8806064/4492191/55c1577c-4a3f-11e4-9d63-f3d4bc68b110.png)

![2](https://cloud.githubusercontent.com/assets/8806064/4492203/6195fdd2-4a3f-11e4-9234-54c309195188.PNG)

**Comment by samat89** [comment]
Changeset 2401
ServiceSearchCtrl.js, multiselect.js, MultiSelectTmpl.html, FlightSearch.html
