### ISSUE TITLE
Search Hotels - Price Update no update in the sum

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#109]
1. click on price in result

2.add sum in extra

3.click button update price

4.click on add to order

5.not update to text box extra in price customer

![1](https://cloud.githubusercontent.com/assets/8806064/4517850/8b2f24d2-4c5d-11e4-9850-c605db3e1ea8.png)
![2](https://cloud.githubusercontent.com/assets/8806064/4517851/8e476dd2-4c5d-11e4-9a2d-dae9848aab39.PNG)

**Comment by AlexSin15** [comment]
Changeset 2387
