### ISSUE TITLE
Departure/Return autocomplete in flight search panel needs multiselect option

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#11]
Fix also server side! (interfaces)

**Comment by suhrab** [comment]
Need screenshots

**Comment by YairChen** [comment]
Today - not good:
![11](https://cloud.githubusercontent.com/assets/7251658/4318811/5dad944a-3f23-11e4-8385-501502333ee2.JPG)

Need to be:
![12](https://cloud.githubusercontent.com/assets/7251658/4318812/6529bc62-3f23-11e4-9ae2-d71bcf8104bd.jpg)

**Comment by rem4ik4ever** [comment]
Was working on multiselect and came up with that. Any comments? This is only visual change, no server side yet implemented and nothing is commited yet.

![multiselect](https://cloud.githubusercontent.com/assets/3874496/4370307/704dd23a-4307-11e4-8fd0-f806168b82dc.PNG)

**Comment by rem4ik4ever** [comment]
Got some results. On screenshot you can see multiple destinations. However I need some tests and overall review to be sure that I didn't affect anything besides flight search. 
![flight multi search](https://cloud.githubusercontent.com/assets/3874496/4403225/15a26db0-44a0-11e4-8584-b96405eeefaf.PNG)

**Comment by rem4ik4ever** [comment]
You might didn't notice but in previous screenshots we have 'undefined' in header of the tab. This is because previosly we had 1 departure and arrival ports. 
![ports-issue](https://cloud.githubusercontent.com/assets/3874496/4416200/141ab37a-453c-11e4-9a1a-57c028c80bdd.PNG)

So the question is could you please send design or some description about how should I manage tab header in case of multiple ports.

**Comment by YairChen** [comment]
Please try to get results with those params: 
from: TLV & SDV   to: ETH

(You tried from: TLV/ETH ...)

**Comment by rem4ik4ever** [comment]
Updated view according to Avi's comments.

![flight-search-tab-header](https://cloud.githubusercontent.com/assets/3874496/4440486/d4a41f60-47c5-11e4-92f8-4bd5a7d242c3.png)

If this design is ok, I can commit changes. @YairChen @yayasoft-simon 

However there is an issue with bs-tooltip directive, if we use a dynamic value like in flight serach where title changes depending on ports tooltip will not appear, unless page is reloaded or digest cycle is re-applied. This directive is in the angular-strap.js .
