### ISSUE TITLE
Sum order - change capacity

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#110]
1. select hotel "isrotel"

2.have validate for name english

3.i want to change capacity

4.but i canot chande because popup of validate there and cannot change this
1. same if i want to change check out

![1](https://cloud.githubusercontent.com/assets/8806064/4517878/4608433a-4c61-11e4-980f-57e58a94777f.png)

**Comment by samat89** [comment]
Changeset 2431
breeze.directive.js, css
