### ISSUE TITLE
Search hotel/flight/package -no show result

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#112]
![1](https://cloud.githubusercontent.com/assets/8806064/4526788/8db6134a-4d62-11e4-8f5e-f8b42da7990d.png)
![2](https://cloud.githubusercontent.com/assets/8806064/4526789/8ec7938a-4d62-11e4-8b36-cdf84a924228.PNG)

**Comment by AlexSin15** [comment]
Problem in Changeset 2400
