### ISSUE TITLE
New OrderSearch ng-grid design

### ISSUE THREAD

**Issue by suhrab** [yayasoft/ytour#121]
![docket - tabular display](https://cloud.githubusercontent.com/assets/4409852/4641467/c02ece1c-5437-11e4-94c4-3ff9d690bd85.png)

.psd
https://mega.co.nz/#!OQ9l1KIL!qMcm5zLU_DSFdU0s3mHRUCW701epXMQC0rQMdgxynP4

page url:
http://localhost:62723/#/orderSearch

**Comment by samat89** [comment]
Changeset 2454
Changeset 2455
Changeset 2457

**Comment by YairChen** [comment]
1. close the filter and then you will see a textbox near the scrolling arrow.
2. why we need to scroll more to see the last column?
   ![11](https://cloud.githubusercontent.com/assets/7251658/4732932/68dff646-59c2-11e4-8f8c-d56d18684745.JPG)

**Comment by simon-sh** [comment]
1) The leftmost column should be visible without scrolling. 
     It is partially hidden because columns widths are not the same as on the design. 
     Please take a measures of the widths and fix the grid according to the design.

   **_Horizontal scrolling still required**_

2) Sorting seems not to be working, please verify/fix it's works (server side)

3) Flexible columns width (the 'native' feature of the ui-grid) - seems not to be working.

4) Grid totals - should be shown in the grid's footer, not below the grid.

**Comment by samat89** [comment]
Changeset 2522

1) Horizontal scrolling not required
2) Sorting implemented
3) Flexibility of columns
4) Grid Totals are made as the footer of ui-grid
5) New field CustomerType "עסקי" is shown properly

**Comment by Avi888** [comment]
![ordersearch-grid-1-01](https://cloud.githubusercontent.com/assets/8790191/5567787/4b49ab5a-8f54-11e4-8e99-36eee055fe13.jpg)
![ordersearch-grid-1-02](https://cloud.githubusercontent.com/assets/8790191/5567788/4b4b4a32-8f54-11e4-853b-4eec1be73129.jpg)
![ordersearch-grid-1-03](https://cloud.githubusercontent.com/assets/8790191/5567786/4b455a32-8f54-11e4-8415-0edfbd7572b0.jpg)
![ordersearch-grid-1-04](https://cloud.githubusercontent.com/assets/8790191/5567790/4b4d5d90-8f54-11e4-8b7b-75173becd2eb.jpg)
![ordersearch-grid-1-05](https://cloud.githubusercontent.com/assets/8790191/5567789/4b4bf7fc-8f54-11e4-970d-e8f318d9afe9.jpg)
![ordersearch-grid-1-06](https://cloud.githubusercontent.com/assets/8790191/5567791/4b4f28d2-8f54-11e4-97cf-1f0e7f4eadfb.jpg)
![ordersearch-grid-1-07](https://cloud.githubusercontent.com/assets/8790191/5567792/4b667820-8f54-11e4-8034-d114250d1967.jpg)
![ordersearch-grid-2-01](https://cloud.githubusercontent.com/assets/8790191/5567793/4b67fd6c-8f54-11e4-9c99-67160b15fc91.jpg)
![ordersearch-grid-2-02](https://cloud.githubusercontent.com/assets/8790191/5567795/4b6b15f6-8f54-11e4-8c2f-f99dab8ca75c.jpg)
![ordersearch-grid-2-03](https://cloud.githubusercontent.com/assets/8790191/5567794/4b698628-8f54-11e4-830f-e7de9000ead6.jpg)

PSD File sent by e-mail
