### ISSUE TITLE
Commission calculation incorrect when selected 2 hotels

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#125]
steps
1.add to order 2 hotel
2.commission of first hotel correct
3.commission of second hotel not calculation
4.if delete service and select just second hotel commission is correct

![1](https://cloud.githubusercontent.com/assets/8806064/4720597/2fcd1f04-5932-11e4-8cac-bba1ecc5d805.png)

![2](https://cloud.githubusercontent.com/assets/8806064/4720601/332408e8-5932-11e4-9a80-c5945d657d2b.PNG)

**Comment by novice3030** [comment]
should be ok now please check and close the bug if it's ok
