### ISSUE TITLE
not change price if update capacity

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#127]
1. search eilat 30/10-2/11 hotel " הים האדום" to 2 adult and add it to order
   2.add 1 child in sum order
2. click search
   4."נמצאה תוצאה מתאימה"

problem 

not change price

![1](https://cloud.githubusercontent.com/assets/8806064/4782475/1f2acc42-5cf6-11e4-8069-cd0b82fd5fd3.png)

![2](https://cloud.githubusercontent.com/assets/8806064/4782478/26fae484-5cf6-11e4-8f82-987dbe40e164.PNG)

**Comment by novice3030** [comment]
sometimes a child doesn't cost extra money
need to check what comming back from hotelligence and make sure that the logic does work

**Comment by yosi-yaya** [comment]
i cheched have extra to child
