### ISSUE TITLE
Increased commission in flight is wrong

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#128]
1.add flight to order
2.in tab Increased commission add 1%
3.is crushed

![1](https://cloud.githubusercontent.com/assets/8806064/4782529/15a42774-5cf9-11e4-8832-c82970758f57.png)

**Comment by AlexSin15** [comment]
How it should be?

**Comment by simon-sh** [comment]
Backspace in 'sum' field - something wrong

**Comment by AlexSin15** [comment]
Changeset 2504
