### ISSUE TITLE
new customer-clear fields

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#13]
1) Add new customer from the link in the order level
![1](https://cloud.githubusercontent.com/assets/8789505/4285368/f0ca63f6-3d85-11e4-8cf4-aa793c3835c4.png)

2)  Save the first customer. Add another one.

![2](https://cloud.githubusercontent.com/assets/8789505/4285389/2060aad0-3d86-11e4-864e-fad0a92703f2.png)

Problem:
when adding a new customer from customers popup under the order the date of birth textbox is not cleared if a customer was already selected before we added the new one

**Comment by AlexSin15** [comment]
Done. Please check.
