### ISSUE TITLE
Package or flight manualy -add tax

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#132]
1. add package or flight
2. add tax

problem

It takes into account the field of profit
this incorrect

![1](https://cloud.githubusercontent.com/assets/8806064/4783272/646a4b2e-5d1f-11e4-94a8-2c0d63016aef.png)

**Comment by AlexSin15** [comment]
How it should be?

**Comment by suhrab** [comment]
Profit = TotalPrice - NetPrice
Net is how what i pay to the provider and TotalPrice is what the customer is paying the agency so profit is TotalPrice - NetPrice

**Comment by YairChen** [comment]
You forgot the tax.
You should look in the code:
NetPrice = GrossPrice -CommissionAmount -ExtraCommissionAmount;
ProfitAmount = TotalPrice - (NetPrice + Tax)

**Comment by AlexSin15** [comment]
Changeset 2499. Please check.
