### ISSUE TITLE
Add payment -Type of payment

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#134]
1.click add payment
2.select type of payment=regular(1 payment)

problem
i can select in field num of payment
if select in type of payment -regular
no enable the field -num of payment
should be just 1 payment

![1](https://cloud.githubusercontent.com/assets/8806064/4808431/a0a258de-5ea0-11e4-95a8-9150caf4524e.png)

**Comment by samat89** [comment]
ChangeSet 2507
should be just 1 payment
Also ddl is disabled
