### ISSUE TITLE
screen add payment -defualt value

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#135]
1.add payment 

should be default value in fields marked

![1](https://cloud.githubusercontent.com/assets/8806064/4810002/01a0fe4c-5eb0-11e4-89b9-fd3f44518c5e.png)

**Comment by YairChen** [comment]
Yossi, please mention the defaults for each field.

**Comment by yosi-yaya** [comment]
1.terminal-defualt terminal(system setup)
2.type of payment-regular
3.num of paymemnt-if regular =1 if payment=2
4.currency-currency of order
5.currency rate-1

**Comment by samat89** [comment]
ChangeSet 2507
