### ISSUE TITLE
save proposal order or order and click new order 

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#137]
no open new order

![1](https://cloud.githubusercontent.com/assets/8806064/4811468/6da81b3e-5eba-11e4-8100-e4c906c41e20.png)

![2](https://cloud.githubusercontent.com/assets/8806064/4811516/db1167b6-5eba-11e4-8269-a7b6c35aba26.PNG)

**Comment by simon-sh** [comment]
```
$scope.newOrder = function () {
        orderContext.createNewOrder();
        $location.url('/preOrder');
    }
```

$location.path('/preOrder') -> $location.url('/preOrder');

Problem: there is query param 'Id' after saving order: /#/preOrder/?Id=$order_id
Solution: remove query string by setting url

This will reset preOrder && hide order details
