### ISSUE TITLE
currency ddl in search results  doesn't works corrent

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#14]
1) select "Tourist" and search by the example in the screenshot
2) Got results in USD. 
3) Select NIS from the currency ddl.
Problem: the results still in USD
![1](https://cloud.githubusercontent.com/assets/8789505/4285595/8deb11ec-3d88-11e4-84fd-753f2f851e38.png)

4) Select USD from the currency ddl.
Problem: wrong results: USD converted to USD (using NIS exchenage rate)
![2](https://cloud.githubusercontent.com/assets/8789505/4285600/99e2609a-3d88-11e4-8a9d-e9a8010f8285.png)
![3](https://cloud.githubusercontent.com/assets/8789505/4285603/9de4f464-3d88-11e4-869f-772ccc8730a1.png)

**Comment by AlexSin15** [comment]
Need to discuss how to make it.
(pressed the wrong button)

**Comment by YairChen** [comment]
Alex, this task is priority B. Finish the A tasks first.

**Comment by AlexSin15** [comment]
Finished. Please check.
Changeset: 2273

**Comment by novice3030** [comment]
changeset 2273 had lots of problems!!!
i reverted this changeset.
please talk to me or @yayasoft-simon before redoing this bug

**Comment by YairChen** [comment]
Alex please finish this bug according to our meeting this mornning

**Comment by AlexSin15** [comment]
Have chaeck-in. Changeset 2323. Please check.

**Comment by simon-sh** [comment]
Selecting different tourist type should reset the default currency.

Repro steps:

1) Select 'Tourist' as tourist type
2) Do the search. (Everything is OK - prices in USD)
3) Select 'Israely', and do the search.

Problem: prices are in USD, should be in NIS

**Comment by AlexSin15** [comment]
Checked, everything works. Need to talk.
This is because rollback my changeset.

**Comment by AlexSin15** [comment]
Check please.

**Comment by simon-sh** [comment]
Changeset 2364 by Alex
