### ISSUE TITLE
Package or flight manualy -add tax

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#144]
Repro steps:
1. Create manual package
   2 .Add package
   3 .Set costs as follow: Gross: 1000, Tax: 100, Commission: 200

Problem:
TotalToPay NOT equal to the TotalPrice

Expected:
TotalToPay equal to the TotalPrice (1100)

![1](https://cloud.githubusercontent.com/assets/8789505/5032456/8e55215c-6b66-11e4-80a2-e9bb5d6080eb.PNG)

**Comment by simon-sh** [comment]
YTourDBContext.js, this.reCalc = function (calcBy) line 1091 <- you might start from here

**Comment by AlexSin15** [comment]
Changeset 2603
