### ISSUE TITLE
select airport in flight

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#145]
1. add airport tlv by click on tlv
2. it add in list
3. but not add in multiply field-"שדות נבחרו 1"

![1](https://cloud.githubusercontent.com/assets/8806064/4881761/17db5bac-634d-11e4-9bdb-5383dc11e7f3.png)
![2](https://cloud.githubusercontent.com/assets/8806064/4881762/1a866c52-634d-11e4-9dc9-d91211701abd.PNG)
![3](https://cloud.githubusercontent.com/assets/8806064/4881763/1dedd11e-634d-11e4-87bb-0a367c2db91f.PNG)

**Comment by samat89** [comment]
The problem occurs in following retro-step:
1. add airport tlv by click on tlv
2. Delete this airport on header of select, pushing 'x' button
it add in list, but not add in multiply field-"שדות נבחרו 1"
