### ISSUE TITLE
Search Menu

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#151]
![menudisable](https://cloud.githubusercontent.com/assets/8790191/4914127/0751324e-64be-11e4-983c-6cc609881931.jpg)

**Comment by feigale** [comment]
![151](https://cloud.githubusercontent.com/assets/8790628/6184970/be50af42-b392-11e4-824b-c1ff982bad53.jpg)

**Comment by AlexSin15** [comment]
Changeset 3174
