### ISSUE TITLE
More passengers PopUp

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#152]
![popup-more-passengers](https://cloud.githubusercontent.com/assets/8790191/4917121/e02eb2f4-64e0-11e4-8888-ab91e55844c4.jpg)

**Comment by feigale** [comment]
![152](https://cloud.githubusercontent.com/assets/8790628/6185012/4bc46fda-b393-11e4-8cf8-57d5f7c83ba8.jpg)

**Comment by AlexSin15** [comment]
Changeset 3175

**Comment by Avi888** [comment]
One Repair that wasn't made:

![more-passengers-popup](https://cloud.githubusercontent.com/assets/8790191/6325712/2f0bab02-bb53-11e4-95fa-299a62944cc4.jpg)

**Comment by feigale** [comment]
Текст на кнопке должен быть 12 пикс.

**Comment by AlexSin15** [comment]
Changeset 3208
