### ISSUE TITLE
Room edit popup

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#153]
![roomedit-popup](https://cloud.githubusercontent.com/assets/8790191/4917333/70e0a67a-64e3-11e4-8704-e707576d18e6.jpg)

**Comment by feigale** [comment]
![153](https://cloud.githubusercontent.com/assets/8790628/6185099/58416294-b394-11e4-86a4-443f1dbcdc03.jpg)

**Comment by AlexSin15** [comment]
Changeset 3179

**Comment by Avi888** [comment]
Same comment as issue #152

**Comment by AlexSin15** [comment]
Changeset 3208
