### ISSUE TITLE
Edit result details PopUp - Hotel one room

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#154]
![edit-details-result-hotel-01-1](https://cloud.githubusercontent.com/assets/8790191/4917809/c35b7bfe-64e9-11e4-91d4-8a38755edc4d.jpg)
![edit-details-result-hotel-01-2](https://cloud.githubusercontent.com/assets/8790191/4917808/c357ae52-64e9-11e4-958c-bc4806429265.jpg)
![edit-details-result-hotel-01-3](https://cloud.githubusercontent.com/assets/8790191/4917806/c352ab82-64e9-11e4-88ff-f7cb2e96f832.jpg)
![edit-details-result-hotel-01-4](https://cloud.githubusercontent.com/assets/8790191/4917807/c35688c4-64e9-11e4-8b74-47e82fe523b0.jpg)
![edit-details-result-hotel-01-5](https://cloud.githubusercontent.com/assets/8790191/4917805/c349f870-64e9-11e4-9aae-3c3191038bb8.jpg)
![edit-details-result-hotel-01-6](https://cloud.githubusercontent.com/assets/8790191/4917810/c36f7cee-64e9-11e4-8374-50d19d937aa7.jpg)
![edit-details-result-hotel-01-7](https://cloud.githubusercontent.com/assets/8790191/4917811/c3735986-64e9-11e4-9424-59513956936b.jpg)

**Comment by feigale** [comment]
1. Подогнать размер попапа точно под дизайн
2. В случае, когда номер (в отеле) только один, не нужна вся верхняя часть
3. Подровнять рамки и расстояния
4. Не хватает стрелочек
5. Подогнать под дизайн текст на кнопке - стиль и размер
6. Приблизить попап к цене, из которой он открывается
7. Неправильное затенение - слишком большое и недостаточно прозрачное

**Comment by AlexSin15** [comment]
Changeset 3191

**Comment by Avi888** [comment]
One Repair that wasn't made:

![edit-result-details-popup](https://cloud.githubusercontent.com/assets/8790191/6326140/350f7296-bb57-11e4-8022-4e408f7b0e50.jpg)

**Comment by feigale** [comment]
Расстояние над кнопкой должно быть 15 пикс., а под - 10 пикс.

**Comment by AlexSin15** [comment]
Changeset 3209
