### ISSUE TITLE
Edit result details PopUp - Hotel multi room

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#155]
![edit-details-result-hotel-02-2](https://cloud.githubusercontent.com/assets/8790191/4917830/fe086a78-64e9-11e4-806f-519e3c0a4fdd.jpg)
![edit-details-result-hotel-02-3](https://cloud.githubusercontent.com/assets/8790191/4917831/fe0b0cb0-64e9-11e4-8d6d-4c4ca84ef708.jpg)
![edit-details-result-hotel-02-4](https://cloud.githubusercontent.com/assets/8790191/4917829/fe075fe8-64e9-11e4-980b-677f01a2e495.jpg)

**Comment by feigale** [comment]
1. Номер слишком высокий - выровнять с текстом
2. Убрать разделительную черту между номерами
3. Сделать расстояния по дизайну

**Comment by AlexSin15** [comment]
Changeset 3191

**Comment by Avi888** [comment]
Same as issue #154

**Comment by AlexSin15** [comment]
Changeset 3209
