### ISSUE TITLE
hotel Information popup

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#158]
![hotel-information-popup-01-4](https://cloud.githubusercontent.com/assets/8790191/4932423/6ef0f634-6589-11e4-81b1-758100e1b77f.jpg)
![hotel-information-popup-01-2](https://cloud.githubusercontent.com/assets/8790191/4932424/6ef377e2-6589-11e4-8961-3e763c08c203.jpg)
![hotel-information-popup-01-5](https://cloud.githubusercontent.com/assets/8790191/4932425/6ef3a6a4-6589-11e4-8508-611bb2a12214.jpg)
![hotel-information-popup-02-1](https://cloud.githubusercontent.com/assets/8790191/4932422/6eeeb400-6589-11e4-9aec-eb774b97a9b6.jpg)
![hotel-information-popup-01-6](https://cloud.githubusercontent.com/assets/8790191/4932421/6eee3e94-6589-11e4-801c-6e0f01b03207.jpg)
![hotel-information-popup-01-3](https://cloud.githubusercontent.com/assets/8790191/4932427/6f1097c8-6589-11e4-88a0-8c6b005654d0.jpg)
![hotel-information-popup-01-8](https://cloud.githubusercontent.com/assets/8790191/4932428/6f133faa-6589-11e4-8df5-1c5e339ce7f5.jpg)
![hotel-information-popup-02-2](https://cloud.githubusercontent.com/assets/8790191/4932426/6f0d5716-6589-11e4-9d32-b3d7f0ccd17a.jpg)
![hotel-information-popup-01-7](https://cloud.githubusercontent.com/assets/8790191/4932430/6f1967d6-6589-11e4-816e-e65fddd00f78.jpg)
![hotel-information-popup-01-9](https://cloud.githubusercontent.com/assets/8790191/4932429/6f18c538-6589-11e4-9f04-57fcd0812871.jpg)
![hotel-information-popup-01-1](https://cloud.githubusercontent.com/assets/8790191/4932432/6f304366-6589-11e4-9148-a7c33886db9d.jpg)
![hotel-information-popup-02-3](https://cloud.githubusercontent.com/assets/8790191/4932431/6f2f8e6c-6589-11e4-8029-81b85e008cf4.jpg)
![hotel-information-popup-02-4](https://cloud.githubusercontent.com/assets/8790191/4932433/6f35444c-6589-11e4-9aab-14ba1210fb07.jpg)

**Comment by feigale** [comment]
1. Красный фон не доходит до конца рамки
2. Подогнать таблицу под дизайн  - размер шрифта в заголовке, цвет фона таблицы, размер таблицы, столбцы
3. Выровнять тексты в таблице
4. Не хватает разделительной линии между типами комнат
5. Упорядочить расстояния по дизайну
6. Стрелочки, при помощи которых листать, не по дизайну
7. Pagination в центре
8. Неправильная ширина меню
9. Неверный размер заголовка

**Comment by Avi888** [comment]
Corrections were sent by e-mail to Tania and to Roman

**Comment by feigale** [comment]
![hotel-information-popup-01-1](https://cloud.githubusercontent.com/assets/8790628/6347493/ad73822c-bc42-11e4-8602-1d80a562848a.jpg)
![hotel-information-popup-01-2](https://cloud.githubusercontent.com/assets/8790628/6347494/ad7584fa-bc42-11e4-894e-3b146561c2d6.jpg)
![hotel-information-popup-01-3](https://cloud.githubusercontent.com/assets/8790628/6347495/ad75e8dc-bc42-11e4-8c81-b1d2e0b75468.jpg)
![hotel-information-popup-01-4](https://cloud.githubusercontent.com/assets/8790628/6347497/ad77083e-bc42-11e4-8532-6bd2c425862e.jpg)
![hotel-information-popup-01-5](https://cloud.githubusercontent.com/assets/8790628/6347496/ad771a18-bc42-11e4-9656-f8f7e12153cf.jpg)
![hotel-information-popup-02-1](https://cloud.githubusercontent.com/assets/8790628/6347498/ad7a8108-bc42-11e4-8803-a09c44cb36f9.jpg)
![hotel-information-popup-02-2](https://cloud.githubusercontent.com/assets/8790628/6347499/ad9da372-bc42-11e4-8e14-a428ab60b943.jpg)
![hotel-information-popup-02-3](https://cloud.githubusercontent.com/assets/8790628/6347500/ada3c31a-bc42-11e4-8dbe-6a27f80cb8bf.jpg)
![hotel-information-popup-02-4](https://cloud.githubusercontent.com/assets/8790628/6347503/ada53268-bc42-11e4-94d3-15ffd14cf98e.jpg)
![hotel-information-popup-02-5](https://cloud.githubusercontent.com/assets/8790628/6347501/ada49e0c-bc42-11e4-85ec-a14e3ef02e27.jpg)
![hotel-information-popup-02-6](https://cloud.githubusercontent.com/assets/8790628/6347504/ada743c8-bc42-11e4-94ef-822068dad7ba.jpg)
![hotel-information-popup-03-1](https://cloud.githubusercontent.com/assets/8790628/6347502/ada50ec8-bc42-11e4-9372-e8b861668427.jpg)
![hotel-information-popup-03-2](https://cloud.githubusercontent.com/assets/8790628/6347505/adc7a0dc-bc42-11e4-923e-423308df8fa8.jpg)
![hotel-information-popup-03-3](https://cloud.githubusercontent.com/assets/8790628/6347506/adced65e-bc42-11e4-8bde-a55d8c9a8c10.jpg)
![hotel-information-popup-03-4](https://cloud.githubusercontent.com/assets/8790628/6347507/add26b70-bc42-11e4-8980-d91910cfb75b.jpg)

**Comment by web4social** [comment]
i can`t find function for "Send to customer", it`s not realized. the other points I`ve done
