### ISSUE TITLE
Gift and comment popup

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#159]
![gift-and-comment-popup-02-2](https://cloud.githubusercontent.com/assets/8790191/4932534/a7c42fac-658a-11e4-84f5-a145abe578a6.jpg)
![gift-and-comment-popup-01-2](https://cloud.githubusercontent.com/assets/8790191/4932535/a7c81478-658a-11e4-8534-550996dc9459.jpg)
![gift-and-comment-popup-01-1](https://cloud.githubusercontent.com/assets/8790191/4932537/a7cd3444-658a-11e4-8b30-23574572a1d9.jpg)
![gift-and-comment-popup-02-1](https://cloud.githubusercontent.com/assets/8790191/4932533/a7c33480-658a-11e4-9979-a08095fe41f0.jpg)
![gift-and-comment-popup-02-3](https://cloud.githubusercontent.com/assets/8790191/4932536/a7c8497a-658a-11e4-9911-ab1f963e9fef.jpg)

**Comment by feigale** [comment]
1. (все комментарии под номером 1) убрать белую рамку
2. (все комментарии под номером 2) размер шрифта неверный. Сделать равнение по правому краю.
3. пока что НЕ менять иконку

**Comment by AlexSin15** [comment]
Changeset 3173

**Comment by Avi888** [comment]
Additional correction:

![gift-and-comment-popup](https://cloud.githubusercontent.com/assets/8790191/6329302/b721a1c6-bb77-11e4-9181-d38dd0579035.jpg)

**Comment by feigale** [comment]
Постоянная ширина ПопАпа 266 пикс, в независимости от длины текста, а вот высота меняется от длины текста. Минимальная высота 100 пикс.

**Comment by AlexSin15** [comment]
Changeset 3210
