### ISSUE TITLE
client's or provider's comments in service tab should be blocked to edit 

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#16]

**Comment by AlexSin15** [comment]
It is done. Roma have did. Please check.

**Comment by novice3030** [comment]
Simon please confirm and close this bug

**Comment by YairChen** [comment]
Sorry, I had a mistake. 
it should be open to edit.
The init text shuld be: remark TO the client  (not from the provider) "הערה ללקוח"
remark TO provider (not from the provider) "הערה לספק"
![3](https://cloud.githubusercontent.com/assets/7251658/4301535/4384fc08-3e50-11e4-88d0-33be58faeba9.JPG)
