### ISSUE TITLE
set price hotel .discount of price customer no correct

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#160]
1.add hotel to order
2.click on set price hotel
3.change price of hotel from 1070 to 1000

problem 

in price customer not correct 

![1](https://cloud.githubusercontent.com/assets/8806064/4936717/8b8318bc-65bc-11e4-8162-535efed674fb.png)

![2](https://cloud.githubusercontent.com/assets/8806064/4936718/8c4e2e26-65bc-11e4-8911-fbedffd97422.PNG)

![3](https://cloud.githubusercontent.com/assets/8806064/4936723/8f6fe5ea-65bc-11e4-807c-bb3c72647f78.PNG)

![4](https://cloud.githubusercontent.com/assets/8806064/4936726/91eae5ae-65bc-11e4-86b9-2ae940f3f7c8.PNG)

**Comment by yosi-yaya** [comment]
זה קורה רק אם מכניסים 1000 או 10000 וכן הלאה
כמו כן זה קורה רק בהזמנת ממשק שמשנים לה את המחיר
אבל בהזמנה ידנית זה בסדר

**Comment by yosi-yaya** [comment]
אני רואה שזה קורה גם בסכומים אחרים

**Comment by web4social** [comment]
Yosi please check It, I just commited
