### ISSUE TITLE
invoice-vat percent

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#168]
vat percent must to be constant (system)
It can't change

![1](https://cloud.githubusercontent.com/assets/8806064/4967485/25152baa-6815-11e4-9246-2d3b46962e0f.png)

Repro steps:

1) Open existing order (for instance, 1809)
2) Click upon "Financial info" tab
3) Click upon "New invoice" tab
4) Select (set checked) first service
5) Reduce invoice sum from 570 to 100

Problems:
- VAT changed to 17.99%
- View is broken

![1](https://cloud.githubusercontent.com/assets/8789505/5163564/e151da68-73d5-11e4-9594-a09af5f05fe0.PNG)

![2](https://cloud.githubusercontent.com/assets/8789505/5163569/eca2c062-73d5-11e4-9d8a-d347bfe2b686.PNG)

![3](https://cloud.githubusercontent.com/assets/8789505/5163576/06506000-73d6-11e4-9aa4-540c325e41e9.PNG)

**Comment by DamirHaibullin** [comment]
Changeset 2681 - resolve bug.
