### ISSUE TITLE
invoice-sum of service in order

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#169]
1.add invoice
2.add 1 service in order
3. change sum of service in invoice-click on btn backspace
it delete service
4. add again the service

problem

it add more service in -"מס שירותים בחשבונית"

![1](https://cloud.githubusercontent.com/assets/8806064/4967500/68f861d8-6816-11e4-913c-f5cf60d5950f.png)

**Comment by samat89** [comment]
Changeset 2599
Invoice.html, InvoiceController.js
