### ISSUE TITLE
Change date of order -no change order to dirty

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#175]
1. add order from date 30/11-04/12
2. change date to 30/11-02/12

problem 

the order no change to status dirty

![1](https://cloud.githubusercontent.com/assets/8806064/5157303/b4e7cc50-730b-11e4-8f3d-5af24a3bdded.PNG)

![2](https://cloud.githubusercontent.com/assets/8806064/5157304/b727d9e2-730b-11e4-8cb4-84e6265fc3a6.PNG)

**Comment by DamirHaibullin** [comment]
Changeset 2679 - resolve bug.
