### ISSUE TITLE
Service gross textbox - value changed by mouse scroll event

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#19]
Need to add unfocus on scroll?
![1](https://cloud.githubusercontent.com/assets/8789505/4285767/d44820a6-3d8a-11e4-9626-731debce94bd.png)

**Comment by web4social** [comment]
Solved by adding directive, which disabled change value in  all input by scroll
Changeset 2237

**Comment by novice3030** [comment]
this is an html5 issue try `<input type="text" step="any">`
i dont think we need a directive for that

**Comment by YairChen** [comment]
Roman, please finish this bug according to our meeting this mornning

**Comment by web4social** [comment]
I deleted type="number" in this input, everything works fine
