### ISSUE TITLE
PPC-results grid - Document type in 3 letters only

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#190]

**Comment by novice3030** [comment]
Please provide the correct 3 chars code for each document type

**Comment by YairChen** [comment]
You have it in the spec document  on chapter 13.4:
TXI - invoice
CTXI - Commission invoice
TXIRCT - InvoiceReceipt (Not implemented yet) 
RCT - receipt
VCH - voucher
RFD - refund
PTXI - Provider Invoice
RMT - pay order
PRQ - pay order request (Not implemented yet) 
DC - debit note
CD - credit note
DPST - Deposit
WDR - Withdrawal

**Comment by novice3030** [comment]
Batch is missing how about BTH

**Comment by novice3030** [comment]
Added all the missing filters for all the document types
From now on if you want to display a document type code and not it's full name just use documentType3Chars filter

**Comment by YairChen** [comment]
Batch is not a accounting document.
It is not have any money meaning.
Batch is only a collection of other accounting documents.

**Comment by novice3030** [comment]
But you still need a 3 chars code for this document because you can search for it and see it in PPC grid results

**Comment by itzik182** [comment]
I'm fixed in PPC filter
