### ISSUE TITLE
cant update field of discount 

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#197]
1. add hotel to order
   2.update discount to customer price- can't add it is crushed

![1](https://cloud.githubusercontent.com/assets/8806064/5201992/e5a8bc78-7581-11e4-8861-be2ad6569245.PNG)

**Comment by yosi-yaya** [comment]
this not working
set discount in sum service
and set discount in customer price 
is crushed

**Comment by samat89** [comment]
Changeset 2920
There was circular actions, so discount cannot be updated

**Comment by novice3030** [comment]
Discount amount only works ok in room service level.
When you want to cahnge it in hotel service level it doesn't work.
Please recheck and fix
