### ISSUE TITLE
manually hotel - not update commision in sum services

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#198]
1.add manually order hotel
2.add commision 20%

problem

not update commision in sum service

![1](https://cloud.githubusercontent.com/assets/8806064/5202369/225e5a48-7586-11e4-8af3-05675e3a464a.PNG)

**Comment by novice3030** [comment]
This is still not fixed please fix it ASAP
If you still can't reproduce talk to Yossi, I can reproduce.
