### ISSUE TITLE
Booking search filter

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#20]
![booking-search-filter-01](https://cloud.githubusercontent.com/assets/8790191/4285893/41b1e3f6-3d8c-11e4-9888-d90529851f80.jpg)
![booking-search-filter-02](https://cloud.githubusercontent.com/assets/8790191/4285892/41a7f8a0-3d8c-11e4-8cf4-7008f8e039cb.jpg)

**Comment by feigale** [comment]
![41b1e3f6-3d8c-11e4-9888-d90529851f80](https://cloud.githubusercontent.com/assets/8790628/4333870/34a59c78-3fe6-11e4-9b77-eba7adf30546.jpg)

**Comment by feigale** [comment]
![41a7f8a0-3d8c-11e4-8cf4-7008f8e039cb](https://cloud.githubusercontent.com/assets/8790628/4333896/8ddfdfe2-3fe6-11e4-8098-e64287789bd6.jpg)

**Comment by Avi888** [comment]
התיקונים הגרפיים בוצעו, יש עדיין בעיות בתפעול דרך האייקונים שעל בר ההרחבה/צמצום

**Comment by Avi888** [comment]
Graphic revisions were made
There are still problems in the operation through the icons on the expansion / reduction bar

**Comment by Avi888** [comment]
![icons-on-the-expansion-reduction-bar](https://cloud.githubusercontent.com/assets/8790191/4735998/b3b4ff8e-59e7-11e4-9fc5-7665f9fdfa63.jpg)

**Comment by feigale** [comment]
![20](https://cloud.githubusercontent.com/assets/8790628/4736119/4e7c2370-59e9-11e4-9f47-17eb07acfc9a.jpg)

**Comment by AlexSin15** [comment]
Changeset 2464
