### ISSUE TITLE
over commisssion in duplicate service hotel

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#201]
1.add to order hotel in base commission 15%
2.duplicate service
3.in over commission set 10%

problem
the profit is 35%
the neto price no correct

![1](https://cloud.githubusercontent.com/assets/8806064/5263379/3816d04c-7a39-11e4-9117-ab1147db3343.PNG)

**Comment by web4social** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/8788244/5338748/cf2c79a6-7f01-11e4-8b1e-c4d0c50a163f.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/8788244/5338747/cf2be89c-7f01-11e4-9985-106812f264c9.png)
What is wrong on this screenshots, please note as it should be

**Comment by yosi-yaya** [comment]
neto price= bruto price -(commission amount+extra commisionamount)
profit percent = (commission amount+extra commision amount)/customer price

**Comment by suhrab** [comment]
This links to #202

**Comment by suhrab** [comment]
Please write it like the following:

1) Create, HotelService with 1room:
Initial Gross: 4000, Comission, Net etc... (All accounting values)

2) I set comission for whole HotelService to 10%

3)Do room duplicate, now 2rooms, I need:
The correct accounting for each room
The correct accounting for whole HotelService

4)After Delete 1room, I need:
The correct accounting for each remaining room
The correct accounting for whole HotelService

N) ...

**Comment by yosi-yaya** [comment]
OK
1.create hotelservice with 1 room
25/12-28/12 hotel "הים האדום" ,inital gross 1100, comission 20%,net 880 , customer price 1100

2.set extra comission 10% total extra comission =110,net price =770
and profit = 30%

this is correct

when the scenario different that:

1.create hotelservice with 1 room
25/12-28/12 hotel "הים האדום" ,inital gross 1100, comission 20%,net 880 , customer price 1100

2.duplicte room

3.set extra comission 10% total extra comission =220
the profit is change 40%
this no correct

because
the correct net price should be 770 per room
so the profit should be 30%
it calculate all extra comission amount per room

**Comment by AlexSin15** [comment]
This links to #216

**Comment by samat89** [comment]
Changeset 2935
