### ISSUE TITLE
over commission-profit if delete service after 

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#202]
1.add order
2. duplicate service
3.add over commission-the profit not correct
4.delete service-the profit not change
5.just if update over commision -the profit correct

problem

this not update auto

![1](https://cloud.githubusercontent.com/assets/8806064/5263634/21129432-7a3c-11e4-92be-9e3144906ba3.PNG)

**Comment by suhrab** [comment]
Please write it like the following:

1) Create, HotelService with 1room:
Initial Gross: 4000, Comission, Net etc... (All accounting values)

2) I set comission for whole HotelService to 10%

3)Do room duplicate, now 2rooms, I need:
The correct accounting for each room
The correct accounting for whole HotelService

4)After Delete 1room, I need:
The correct accounting for each remaining room
The correct accounting for whole HotelService

N) ...

**Comment by DamirHaibullin** [comment]
Resolved in https://github.com/yayasoft/ytour/issues/216
