### ISSUE TITLE
field comments from client - can't set field

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#203]
![1](https://cloud.githubusercontent.com/assets/8806064/5264648/4ca05054-7a45-11e4-8e84-fa50e8d8eca8.PNG)

**Comment by AlexSin15** [comment]
Please describe how it should be?

**Comment by AlexSin15** [comment]
Changeset 2919

**Comment by novice3030** [comment]
this is still not fixed!
please fix it and mark as resolved when done

**Comment by suhrab** [comment]
Checked. Works for me
