### ISSUE TITLE
General Service Corrections

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#207]
![general-service-01](https://cloud.githubusercontent.com/assets/8790191/5455382/c8e27468-8543-11e4-8c22-752e845f0329.jpg)
![general-service-02](https://cloud.githubusercontent.com/assets/8790191/5455381/c8e13152-8543-11e4-9cb4-7cf8b5d2faaa.jpg)
![general-service-03](https://cloud.githubusercontent.com/assets/8790191/5455380/c8df2f10-8543-11e4-8fb7-52c0317faff3.jpg)
![general-service-04](https://cloud.githubusercontent.com/assets/8790191/5455378/c8dc624e-8543-11e4-959a-2e4e9720d4c5.jpg)
![general-service-05](https://cloud.githubusercontent.com/assets/8790191/5455379/c8dcc9a0-8543-11e4-9db7-b5f92bed6483.jpg)
![general-service-06](https://cloud.githubusercontent.com/assets/8790191/5455383/c8f53102-8543-11e4-807b-a247e2217d39.jpg)
![general-service-07](https://cloud.githubusercontent.com/assets/8790191/5455385/c90210c0-8543-11e4-9f15-1eed8c250fa4.jpg)
![general-service-08](https://cloud.githubusercontent.com/assets/8790191/5455384/c901f2fc-8543-11e4-96b9-b017fee6a85b.jpg)
![general-service-09](https://cloud.githubusercontent.com/assets/8790191/5455386/c9024478-8543-11e4-8288-7b2a5c2a69e5.jpg)
![general-service-10](https://cloud.githubusercontent.com/assets/8790191/5455387/c90649ec-8543-11e4-8447-466f2d7739d2.jpg)
![general-service-11](https://cloud.githubusercontent.com/assets/8790191/5455388/c90725ce-8543-11e4-889c-6313d71d3eb7.jpg)

**Comment by feigale** [comment]
1.  В состоянии заказа выделенная область в главном меню должна быть «חיפוש» («поиск»)
2.  Неправильная панель иконок (icon bar)
3.  Неверное расстояние – должно быть 10 пикс.
4.  Не хватает заголовка «שירות כללי» (General Service). Даты задаются заранее. Если дата не были введены, должно быть написано «לא הוזנו תאריכים» («не введены даты»)
5.  Выбор валюты заказа не работает (есть лишний серый цвет внутри текстбокса)
6.  Цвет фона текстбокса неправильный
7.  Очень трудно выбирать время (особенно в дате окончания)
8.  Значок валюты отображается в рамке – убрать рамку, значок расположен слишком высоко, нужно выровнять со всеми текстами
9.  Расположение заголовков не подходит к текстбоксам, иконка поиска и иконка билета клиента неверно расположены, лишний выбор дат
10. Дополнительная информация по пассажиру непонятная…
11. Текстбоксы с комментариями расположить рядом друг с другом, а не один под другим

![c9024478-8543-11e4-8288-7b2a5c2a69e5](https://cloud.githubusercontent.com/assets/8790628/5522667/de9963d2-89e6-11e4-82bf-ee77012ea479.jpg)
