### ISSUE TITLE
Order - Increased commission calc is wrong and not showing under room service

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#216]
![image](https://cloud.githubusercontent.com/assets/6697179/5548953/53d95a52-8b87-11e4-94bd-34fc8c126f3b.png)

**Comment by suhrab** [comment]
Look at how comission works

**Comment by AlexSin15** [comment]
Please describe in details how it should be and how much money should get?

**Comment by yosi-yaya** [comment]
in service room should be 20%+3%
now is showing 20%+0%

**Comment by AlexSin15** [comment]
If service have 2 rooms, how it should be?
How much should be in Netto, TotalPrice, etc...?

**Comment by yosi-yaya** [comment]
neto price= bruto price -(commission amount+extra commision amount)
profit percent = (commission amount+extra commision amount)/customer price

**Comment by yosi-yaya** [comment]
This right formula:
neto price= bruto price -(commission amount+extra commision amount)
profit percent=(price customer-neto price)/price customer

**Comment by AlexSin15** [comment]
We have 1 room in service then 20%+3%.
But if we have 2 rooms in service, then 20%+1.5% in each room service?
But if we have 3 rooms in service, then 20%+1% in each room service?

**Comment by YairChen** [comment]
Alex,  you sumerize all the xommosions amount from all the rooms in the service and then divid it with the total gross of the service and then get the percent

**Comment by YairChen** [comment]
Same same with the extra commission amount

**Comment by suhrab** [comment]
We have 2 RoomServices.

When we add extraCommision 10% to HotelService how extra comission should affect the RoomServices?
We were thinking about it and come to several ways:

1) Room Accountings leave not changed. ExtraComission should only change HotelService accounting values
2) Each Room extraCommision increases by 10%. RoomServices accounting reCalc. HotelService gets summarized accountings from all its RoomServices

Which is right? Maybe another way?

**Comment by YairChen** [comment]
When u add 10% extra com it means that for EACH hotel room in the current hotel service we will add 10% of extra com.  I think that is like what u suggest in option 2.

**Comment by AlexSin15** [comment]
Changeset 2933
