### ISSUE TITLE
Order - voucher is not shown after manual/automatic creation in grids

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#218]
The accounting grids should refresh automaticly with the latest data after creating vouchers

**Comment by suhrab** [comment]
For now only for order & docket

**Comment by suhrab** [comment]
http://jira-logisense.cc.kg/browse/YT-156

**Comment by YairChen** [comment]
Ran,  because it connected to the Voucher logic,  I prefer you will fix it.

**Comment by itzik182** [comment]
I fixed it
