### ISSUE TITLE
order - click on "Warning triangle"

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#226]
1.booking order
2.have "Warning triangle"
3.click on Warning triangle

problem
the popup is are you want to cancel it

![1](https://cloud.githubusercontent.com/assets/8806064/5553742/6cfc19ee-8c35-11e4-8043-77e00a0f0eb3.PNG)

![2](https://cloud.githubusercontent.com/assets/8806064/5553743/766156de-8c35-11e4-9dfc-a35b4e28ddac.PNG)

**Comment by web4social** [comment]
I made it to the test, because I do not know where to put the button to close all orders

**Comment by YairChen** [comment]
You mean "Cancel Order". Not close order, right?

**Comment by web4social** [comment]
yes I mean Cancel Order
