### ISSUE TITLE
A1 priority repairs

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#227]
![a1-priority-repairs-01](https://cloud.githubusercontent.com/assets/8790191/5586677/335510f2-90df-11e4-9d7e-a6968f64735e.jpg)

**Comment by feigale** [comment]
![227](https://cloud.githubusercontent.com/assets/8790628/5611333/a52cb356-94ef-11e4-971b-d6ba560c928f.jpg)

**Comment by suhrab** [comment]
@feigale Tanya, paste a corrected word as a comment here

**Comment by samat89** [comment]
Comma between thousand and hundred parts exists, the point on screenshot is just for decimal part of number, for example if TotalPrice= 22725.5 then it is displayed as 22,725.5

**Comment by samat89** [comment]
Changeset 2958
