### ISSUE TITLE
Balance bar

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#228]
![balance-bar-02](https://cloud.githubusercontent.com/assets/8790191/5587226/24c65690-90ee-11e4-83a0-b611f96d594d.jpg)
![balance-bar-01-1](https://cloud.githubusercontent.com/assets/8790191/5587230/24ca6fc8-90ee-11e4-8b8b-c50fd64587e0.jpg)
![balance-bar-04](https://cloud.githubusercontent.com/assets/8790191/5587227/24c7342a-90ee-11e4-8b5b-55ed50b98a09.jpg)
![balance-bar-01-3](https://cloud.githubusercontent.com/assets/8790191/5587228/24c90750-90ee-11e4-83b9-d402837a7f78.jpg)
![balance-bar-03](https://cloud.githubusercontent.com/assets/8790191/5587229/24c9255a-90ee-11e4-85d1-0efb2fac4e65.jpg)
![balance-bar-01-2](https://cloud.githubusercontent.com/assets/8790191/5587231/24e4c1f2-90ee-11e4-9d63-c0ab2be3ecdf.jpg)

PSD file sent via e.mail to Anton & Tanya

**Comment by feigale** [comment]
![1](https://cloud.githubusercontent.com/assets/8790628/5609535/e8c6ea46-94cc-11e4-921f-9b847fa532ff.jpg)
![2](https://cloud.githubusercontent.com/assets/8790628/5609533/e8c453bc-94cc-11e4-9e93-4b3bdd7a21d7.jpg)
![3](https://cloud.githubusercontent.com/assets/8790628/5609534/e8c5daf2-94cc-11e4-8cb0-86771c1162b1.jpg)
![4](https://cloud.githubusercontent.com/assets/8790628/5609537/e8e6f4bc-94cc-11e4-9a1d-5efce317c871.jpg)
![5](https://cloud.githubusercontent.com/assets/8790628/5609536/e8e6d3a6-94cc-11e4-83af-63854046d245.jpg)
![6](https://cloud.githubusercontent.com/assets/8790628/5609538/e8e82b8e-94cc-11e4-876a-35fb0279ba44.jpg)
