### ISSUE TITLE
Order Search grid

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#229]
![ordersearch-grid-1-01](https://cloud.githubusercontent.com/assets/8790191/5587271/fe702182-90ee-11e4-8101-0b0d40b962e3.jpg)
![ordersearch-grid-1-02](https://cloud.githubusercontent.com/assets/8790191/5587269/fe6f31e6-90ee-11e4-9472-84edf200abd4.jpg)
![ordersearch-grid-1-03](https://cloud.githubusercontent.com/assets/8790191/5587272/fe7072c2-90ee-11e4-9061-b69ebda6ac5b.jpg)
![ordersearch-grid-1-04](https://cloud.githubusercontent.com/assets/8790191/5587270/fe6f5a86-90ee-11e4-9f6c-67cdfabc28e8.jpg)
![ordersearch-grid-1-05](https://cloud.githubusercontent.com/assets/8790191/5587273/fe7205d8-90ee-11e4-8965-9f186ad14621.jpg)
![ordersearch-grid-1-06](https://cloud.githubusercontent.com/assets/8790191/5587274/fe869570-90ee-11e4-81b1-5382f388ce19.jpg)
![ordersearch-grid-1-07](https://cloud.githubusercontent.com/assets/8790191/5587276/fe8d36aa-90ee-11e4-925b-ec409e22492e.jpg)
![ordersearch-grid-2-01](https://cloud.githubusercontent.com/assets/8790191/5587277/fe8e711e-90ee-11e4-8832-3070ab2d20ea.jpg)
![ordersearch-grid-2-02](https://cloud.githubusercontent.com/assets/8790191/5587275/fe8babc8-90ee-11e4-8866-3ac6ab3dcdcd.jpg)
![ordersearch-grid-2-03](https://cloud.githubusercontent.com/assets/8790191/5587278/fe90b294-90ee-11e4-9e76-c0b4a968efed.jpg)

**Comment by feigale** [comment]
![1](https://cloud.githubusercontent.com/assets/8790628/5611004/906bd06e-94ea-11e4-9dc0-adb81d47b5e7.jpg)
![2](https://cloud.githubusercontent.com/assets/8790628/5611005/906ddbe8-94ea-11e4-9bdc-06c7b930f9eb.jpg)
![3](https://cloud.githubusercontent.com/assets/8790628/5611007/9078515e-94ea-11e4-90f6-e387e72fa57b.jpg)
![4](https://cloud.githubusercontent.com/assets/8790628/5611006/9072cb44-94ea-11e4-9b68-b1f109dcac1b.jpg)
![5](https://cloud.githubusercontent.com/assets/8790628/5611009/907cfa56-94ea-11e4-9eb6-ff4471f4c8ec.jpg)
![6](https://cloud.githubusercontent.com/assets/8790628/5611008/907b075a-94ea-11e4-87ee-e69ed157f3b6.jpg)
![7](https://cloud.githubusercontent.com/assets/8790628/5611010/9091670c-94ea-11e4-991b-d9e2b2b15954.jpg)
![8](https://cloud.githubusercontent.com/assets/8790628/5611011/909493e6-94ea-11e4-93e1-4ccef33aae8a.jpg)
![9](https://cloud.githubusercontent.com/assets/8790628/5611012/909566ea-94ea-11e4-8652-027519c4af26.jpg)
![10](https://cloud.githubusercontent.com/assets/8790628/5611013/909ea4b2-94ea-11e4-851b-e37565fe113c.jpg)

**Comment by samat89** [comment]
sorting column works properly, except one case:
When we push first time at column, grid sorts data by this column as ascending,
When we push second time, grid sorts data in descending order
When we push third time, it is ability of grid to disable sorting, so third time clicking on column
means, that we don't want to see arrow of sorting

**Comment by samat89** [comment]
DDL is not active now, because there is no logic on that. What this ddl mean?

**Comment by Avi888** [comment]
Type of Currency display on the balance bar

> On 5 בינו׳ 2015, at 14:19, Samat notifications@github.com wrote:
> 
> DDL is not active now, because there is no logic on that. What this ddl mean?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/yayasoft/ytour/issues/229#issuecomment-68700917.

אבי ירמלובסקי Avi Yarmalovski
UI

טלפוןPhone/ :
03-5787772
פקס/Fax :
03-5700549

דוא"לE-mail/ :
aviy@yayasoft.co.i mailto:yaya@yayasoft.co.ili
אינטרנטInternet/ :
http://www.yayasoft.co.il http://www.yayasoft.co.il/
http://www.hotelligence.co.il http://www.hotelligence.co.il/

**Comment by suhrab** [comment]
Could somebody give a spec for DDL "In local currency". List items + each item purpose in details

**Comment by samat89** [comment]
In old version of ui-grid horizontal scrollbar was before footer(balance bar). 
In new version scrollbar is placed after footer.
Also in old version horizontal scrollbar was placed till pinned column, now in new version it is placed till border of grid, so there is no need to white continuing background. 
So, balance bar(footer) will be placed before horizontal scrollbar.
Now in new version it will look like following
![footer](https://cloud.githubusercontent.com/assets/8788263/5613285/dbf25ca8-950b-11e4-9d9e-23e1aefda8ef.png)
According https://github.com/yayasoft/ytour/issues/121
![footer](https://cloud.githubusercontent.com/assets/8788263/5625029/6e2363b6-959c-11e4-8612-5e65b9206fc5.png)

**Comment by novice3030** [comment]
I think "In local currency" is used to display prices in the agency local currency (so price conversion is in order) but ask @YairChen to be sure

**Comment by samat89** [comment]
check box CN RQ is used for filter "Cancel request"

**Comment by samat89** [comment]
DDL for Queue will be implemented properly in http://jira-logisense.cc.kg/browse/YT-129. Now it is just set in bar without logic

**Comment by samat89** [comment]
DDL "In local currency" will be implemented, when it will be clear in 
http://jira-logisense.cc.kg/browse/YT-161

**Comment by samat89** [comment]
Changeset 2954

**Comment by Avi888** [comment]
Some of the fixes were made, I will open a new issue with corrections up to date
