### ISSUE TITLE
X Close

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#230]
![x-close-01](https://cloud.githubusercontent.com/assets/8790191/5605611/488c1264-940d-11e4-92f1-366c814ff0a4.jpg)
![x-close-02](https://cloud.githubusercontent.com/assets/8790191/5605612/488c602a-940d-11e4-86d0-d358fa1ff39f.jpg)

**Comment by feigale** [comment]
![230-1](https://cloud.githubusercontent.com/assets/8790628/5611284/e37bfcf8-94ee-11e4-984d-41977bd6566d.jpg)
![230-2](https://cloud.githubusercontent.com/assets/8790628/5611285/e380945c-94ee-11e4-8b5c-83bd492815c5.jpg)

**Comment by AlexSin15** [comment]
Changeset 2952
