### ISSUE TITLE
Docket Title

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#232]
![docket-title](https://cloud.githubusercontent.com/assets/8790191/5605873/e4266c56-941c-11e4-8c73-5d02e721d7ec.png)

**Comment by feigale** [comment]
![232](https://cloud.githubusercontent.com/assets/8790628/5611108/2785b2de-94ec-11e4-8b91-43d650ebbab2.png)

**Comment by DamirHaibullin** [comment]
Changeset 2957 - fix design and fix logic work icons in OrderToolBar.
