### ISSUE TITLE
QT Service

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#233]
![qt-service](https://cloud.githubusercontent.com/assets/8790191/5606055/cfe595ee-9423-11e4-8345-06e337291314.jpg)

**Comment by feigale** [comment]
1. Статус QT отображается серым цветом, а надо синим
2. На строке услуги "полет" отображается слово Quote зеленого цвета - оно там не должно отображаться совсем

**Comment by suhrab** [comment]
@Avi888 give a web color code for "QT" status. For example "#FF0000" or rgba.

**Comment by Avi888** [comment]
#1a72ad

> On 5 בינו׳ 2015, at 13:31, Anton Anisimov notifications@github.com wrote:
> 
> @Avi888 https://github.com/Avi888 give a web color code for "QT" status. For example "#FF0000" or rgba.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/yayasoft/ytour/issues/233#issuecomment-68696846.

אבי ירמלובסקי Avi Yarmalovski
UI

טלפוןPhone/ :
03-5787772
פקס/Fax :
03-5700549

דוא"לE-mail/ :
aviy@yayasoft.co.i mailto:yaya@yayasoft.co.ili
אינטרנטInternet/ :
http://www.yayasoft.co.il http://www.yayasoft.co.il/
http://www.hotelligence.co.il http://www.hotelligence.co.il/

**Comment by suhrab** [comment]
Changeset 2953
