### ISSUE TITLE
Saving Icon

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#234]
![saving-icon](https://cloud.githubusercontent.com/assets/8790191/5606085/34273b42-9425-11e4-8367-6821fb2cc478.jpg)

**Comment by feigale** [comment]
Когда производятся изменения в сохраненном докете, иконка "сохранить предложение" в боковом меню должна меняться по дизайну

**Comment by suhrab** [comment]
@Avi888 "Save" button should have yellow background when order is already saved ?

**Comment by Avi888** [comment]
Just in case changes have been made

> On 5 בינו׳ 2015, at 13:27, Anton Anisimov notifications@github.com wrote:
> 
> @Avi888 https://github.com/Avi888 "Save" button should have yellow background when order is already saved ?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/yayasoft/ytour/issues/234#issuecomment-68696475.

אבי ירמלובסקי Avi Yarmalovski
UI

טלפוןPhone/ :
03-5787772
פקס/Fax :
03-5700549

דוא"לE-mail/ :
aviy@yayasoft.co.i mailto:yaya@yayasoft.co.ili
אינטרנטInternet/ :
http://www.yayasoft.co.il http://www.yayasoft.co.il/
http://www.hotelligence.co.il http://www.hotelligence.co.il/

**Comment by suhrab** [comment]
@Avi888 please send .PSD for these buttons.

Now background changes to yellow but not like on your screen. I asked guys if they have .psd for these buttons, they don't have

**Comment by Avi888** [comment]
> On 6 בינו׳ 2015, at 07:27, Anton Anisimov notifications@github.com wrote:
> 
> @Avi888 https://github.com/Avi888 please send .PSD for these buttons
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/yayasoft/ytour/issues/234#issuecomment-68827863.

אבי ירמלובסקי Avi Yarmalovski
UI

טלפוןPhone/ :
03-5787772
פקס/Fax :
03-5700549

דוא"לE-mail/ :
aviy@yayasoft.co.i mailto:yaya@yayasoft.co.ili
אינטרנטInternet/ :
http://www.yayasoft.co.il http://www.yayasoft.co.il/
http://www.hotelligence.co.il http://www.hotelligence.co.il/

**Comment by Avi888** [comment]
PSD file were sent by e-mail
