### ISSUE TITLE
Docket - Split view correction

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#235]
Sent by e-mail to Anton, Samat & Tanya

**Comment by suhrab** [comment]
with Russian translation https://mega.co.nz/#!TE8CjYLY!5FM0ARm92fULse7xmORh8PPrxJh-NAiysDiwx-mxx7o

**Comment by DamirHaibullin** [comment]
Changeset 2960 - split view 04(layer in PSD)

**Comment by DamirHaibullin** [comment]
Changeset 2965 - split view 02(layer in PSD)

**Comment by samat89** [comment]
Changeset 2966 - Split View 03

**Comment by samat89** [comment]
Due split arrow selected feature depends on ui-grid scrolling feature, created new issue https://github.com/yayasoft/ytour/issues/236
So, Split View 01 will be done in that issue. In jira it is 
http://jira-logisense.cc.kg/browse/YT-165

**Comment by Avi888** [comment]
There is still a lot of design problems

**Comment by samat89** [comment]
There is a problem with new version of grid, so it will be solved in
https://github.com/yayasoft/ytour/issues/237

**Comment by Avi888** [comment]
I will open a new issue with corrections up to date
