### ISSUE TITLE
Docket Grid Corrections

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#237]
Files sent by e-mail

**Comment by feigale** [comment]
![grid-corrections-02-2](https://cloud.githubusercontent.com/assets/8790628/5699647/276d2f82-9a57-11e4-8435-edfaafba4c6c.jpg)
![grid-corrections-02-3](https://cloud.githubusercontent.com/assets/8790628/5699648/27908e96-9a57-11e4-8bf3-b45ee3a8615a.jpg)
![grid-corrections-02-4](https://cloud.githubusercontent.com/assets/8790628/5699650/27936c42-9a57-11e4-9b57-2224990fb80a.jpg)
![grid-corrections-02-5](https://cloud.githubusercontent.com/assets/8790628/5699649/279287aa-9a57-11e4-9f00-d3ad46af7cf7.jpg)
![grid-corrections-03](https://cloud.githubusercontent.com/assets/8790628/5699652/27964d18-9a57-11e4-88b2-554a95ea4d5b.jpg)
![grid-corrections-04](https://cloud.githubusercontent.com/assets/8790628/5699651/27947ad8-9a57-11e4-8558-976242a1bce8.jpg)
![grid-corrections-05](https://cloud.githubusercontent.com/assets/8790628/5699653/27993726-9a57-11e4-8751-5f20539e94fc.jpg)
![grid-corrections-01-1](https://cloud.githubusercontent.com/assets/8790628/5699655/27b65f4a-9a57-11e4-971d-e38f175fc717.jpg)
![grid-corrections-01-2](https://cloud.githubusercontent.com/assets/8790628/5699657/27bb51da-9a57-11e4-8d98-935b99791e89.jpg)
![grid-corrections-01-3](https://cloud.githubusercontent.com/assets/8790628/5699654/27b6612a-9a57-11e4-9ae0-8a07284ccc5a.jpg)
![grid-corrections-01-4](https://cloud.githubusercontent.com/assets/8790628/5699656/27b73c30-9a57-11e4-98cc-1099c0d9d6bc.jpg)
![grid-corrections-01-5](https://cloud.githubusercontent.com/assets/8790628/5699658/27bbf374-9a57-11e4-8fab-5fc8e7c63f4b.jpg)
![grid-corrections-01-6](https://cloud.githubusercontent.com/assets/8790628/5699659/27bf7d96-9a57-11e4-88fd-2ae6ae8a39ae.jpg)
![grid-corrections-02-1](https://cloud.githubusercontent.com/assets/8790628/5699660/27dd7882-9a57-11e4-9661-6e29d1eb522d.jpg)

**Comment by samat89** [comment]
Arrow for sorted column is added

**Comment by samat89** [comment]
Selection activity in sorted column will be solved in ui-grid stable version

**Comment by samat89** [comment]
The problems with scrolling will be solved in ui-grid stable version

**Comment by samat89** [comment]
In split view mode footer(total data) cannot be shown as in example, because in that case ui-grid footer ability cannot be implemented.

**Comment by samat89** [comment]
Notes not relevant to ui-grid are done.

**Comment by samat89** [comment]
Changeset 3196
