### ISSUE TITLE
Urgent Message

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#238]
![urgent-message](https://cloud.githubusercontent.com/assets/8790191/5661700/66b7573a-9737-11e4-8f14-52cfec784c23.jpg)

**Comment by feigale** [comment]
![238](https://cloud.githubusercontent.com/assets/8790628/5699703/4978a826-9a58-11e4-95dc-7849b96c6172.jpg)

**Comment by AlexSin15** [comment]
Where to get the "Constant Message"? Now it set hard coded.
