### ISSUE TITLE
breeze hasChanges() bug

### ISSUE THREAD

**Issue by web4social** [yayasoft/ytour#239]
There is a bug with breeze EntityManager.hasChanges fn.
Changing some fields in PreOrder screen, gives hasChanges is undefined error
It appeared after upgrading to breeze 1.5.2 client-side

![screenshot_5](https://cloud.githubusercontent.com/assets/4409852/5662203/507be656-9760-11e4-9cd6-5cf861a68e61.png)

**Comment by novice3030** [comment]
this bug was already fixed and will be in 1.5.3 it is also fixed in current breeze souce in github
you can take the fix from there until we move to 1.5.3
