### ISSUE TITLE
provider card - order from and pay to columns doesn't show the data even though in DB it has values

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#241]
repo steps:
1. log in with eshet/test
2. go to provider card
3. search for provider 333
4. go to products/agreement tab

both columns are empty even though it has data in the DB

![image](https://cloud.githubusercontent.com/assets/6697179/5756390/b989a578-9cb7-11e4-9770-308a80d6d47a.png)

**Comment by AlexSin15** [comment]
Changeset 2995
