### ISSUE TITLE
provider card - when editing a product/agreement for a provider some DDL's doesn't get set with the values

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#242]
repo steps:
1. log in with eshet/test
2. go to provider card 333
3. go to products/agreements tab
4. select a record from the grid to edit it
5. product DDL is empty, pay to DDL is empty (even though it has data in the DB)

![image](https://cloud.githubusercontent.com/assets/6697179/5756459/6a54976e-9cb8-11e4-83aa-ba048a1774cb.png)

**Comment by DamirHaibullin** [comment]
Changeset 3024

**Comment by novice3030** [comment]
This is still not fixed
Please recheck it

**Comment by DamirHaibullin** [comment]
This was fixed. 
The _Selected Product_ get through ProductType. In this case _EnityId_ for _ProductType Hotel_ will be equal to the _Id_ from table Hotels. But for _AgencyId=26_ is missing data in the table Hotels, so the _Selected Product_ is empty.

**Comment by novice3030** [comment]
Ok i will update this agency with current hotels we have the system
Good find BTW
