### ISSUE TITLE
SearchScreen

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#246]
![searchscreen01](https://cloud.githubusercontent.com/assets/8790191/5792029/8c4f44cc-9f0b-11e4-9572-3c991cc586ca.jpg)
![searchscreen02](https://cloud.githubusercontent.com/assets/8790191/5792031/8c506f1e-9f0b-11e4-8bdf-6c6ded0a6b67.jpg)
![searchscreen03](https://cloud.githubusercontent.com/assets/8790191/5792030/8c4f51b0-9f0b-11e4-84ad-321121815621.jpg)

**Comment by AlexSin15** [comment]
Changeset 3005
