### ISSUE TITLE
Customer Search (Menu)

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#247]
Corrections were sent by e-mail

**Comment by feigale** [comment]
![customer-search- menu -01-1](https://cloud.githubusercontent.com/assets/8790628/5796713/e917f0de-9fd6-11e4-9785-2c5c5a97403e.jpg)
![customer-search- menu -01-2](https://cloud.githubusercontent.com/assets/8790628/5796714/e93d02b6-9fd6-11e4-89e2-6146bfd1b81d.jpg)
![customer-search- menu -01-3](https://cloud.githubusercontent.com/assets/8790628/5796715/e94eec6a-9fd6-11e4-91fb-686508b6fad1.jpg)
![customer-search- menu -02-1](https://cloud.githubusercontent.com/assets/8790628/5796716/e9567d72-9fd6-11e4-80c6-dabe0cedc405.jpg)
![customer-search- menu -02-2](https://cloud.githubusercontent.com/assets/8790628/5796717/e9574b80-9fd6-11e4-8242-fed10b5e94f8.jpg)
![customer-search- menu -02-3](https://cloud.githubusercontent.com/assets/8790628/5796719/e95bed70-9fd6-11e4-91cc-b9fc58352724.jpg)
![customer-search- menu -03-1](https://cloud.githubusercontent.com/assets/8790628/5796718/e95be8ca-9fd6-11e4-9a81-4eb60027a0cf.jpg)
![customer-search- menu -03-2](https://cloud.githubusercontent.com/assets/8790628/5796720/e95f5f32-9fd6-11e4-9dc5-8cc321de4813.jpg)
![customer-search- menu -03-3](https://cloud.githubusercontent.com/assets/8790628/5796721/e9753b72-9fd6-11e4-9f91-3818bbd15bd8.jpg)
![customer-search- menu -03-4](https://cloud.githubusercontent.com/assets/8790628/5796722/e97af0a8-9fd6-11e4-9080-f501112474d1.jpg)
![customer-search- menu -03-5](https://cloud.githubusercontent.com/assets/8790628/5796723/e97b2c08-9fd6-11e4-8ce6-adb869001b23.jpg)
![customer-search- menu -03-6](https://cloud.githubusercontent.com/assets/8790628/5796724/e981af24-9fd6-11e4-8d31-ec3c8fcd9d98.jpg)
![customer-search- menu -03-7](https://cloud.githubusercontent.com/assets/8790628/5796725/e983b1d4-9fd6-11e4-97d5-9496cde9f666.jpg)

**Comment by web4social** [comment]
I have question about customer filter, multiselect: what values will be searched?

**Comment by novice3030** [comment]
from what i can see the filter is working as expected

it does like on FirstName, LastName, EnglishFirst, EngishLastName

**Comment by web4social** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/8788244/5852869/60917762-a247-11e4-9345-9d368cdbc60f.png)

**Comment by web4social** [comment]
Avi add two new filter, PNR filter I've done, but i'm not understand second filter

**Comment by novice3030** [comment]
When using filter by PNR\Docket number you search for the service that has this PNR or the order that has the docket number and you get the list of customers under the service/order

**Comment by web4social** [comment]
ok, what about second multiselect filter?

**Comment by Avi888** [comment]
Two additional comments:

![customer-search- menu -04-1](https://cloud.githubusercontent.com/assets/8790191/6325550/7ff8350a-bb51-11e4-87a8-e59ada99c66e.jpg)
![customer-search- menu -04-2](https://cloud.githubusercontent.com/assets/8790191/6325549/7ff71f30-bb51-11e4-88db-e7764d2c0ee4.jpg)
![customer-search- menu -04-3](https://cloud.githubusercontent.com/assets/8790191/6325548/7ff31f0c-bb51-11e4-8259-61fabe62e2ac.jpg)

**Comment by feigale** [comment]
Comments' translation:
1. Перевернуть стрелочку
2. Когда строка выделена, иконка карточки клиента и крестик Х должны менять цвет
3. Общие замечания по гриду будут высланы отдельно

**Comment by samat89** [comment]
Changeset 3216

**Comment by samat89** [comment]
Some notes are fixed.
Due grid is unstable, issues on ui-grid will be solved in another issue.
