### ISSUE TITLE
BreezeApi Helper to get data

### ISSUE THREAD

**Issue by samat89** [yayasoft/ytour#248]
In BreezeApi controller there are a lot of additional functions and classes.
I think there should be some class, which should be responsive for logic.
Really logic should be written in helper object, because now in Breeze api controller there are approximately 6000 lines of code.

**Comment by suhrab** [comment]
You can mark BreezeApiController class as **partial**
And create separate c# files. For example for Cashier logic create file BreezeApiController.Cashier.cs
BreezeApiController.Provider.cs
etc..

public partial class BreezeApiController{/_your methods here_/}

**Comment by samat89** [comment]
Changeset 3015
Made it for Queues module
Modules should be placed in folder Controllers/Partials and called properly
e.g. BreezeApiController.Queues.cs

**Comment by samat89** [comment]
http://jira-logisense.cc.kg/browse/YT-178

**Comment by novice3030** [comment]
@suhrab making BreezeApiController partial is a good way to go about it.
I also started taking out stuff from the main class and put it on separated files
I also updated the rest of the team about doing so
