### ISSUE TITLE
Design Corrections - Docket

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#25]
![docket-1](https://cloud.githubusercontent.com/assets/8790191/4288183/e8cfb51a-3da9-11e4-82a4-d446a489e3d2.jpg)
![docket-2](https://cloud.githubusercontent.com/assets/8790191/4288179/e8c09f80-3da9-11e4-9339-d67babaa18b5.jpg)
![docket-3](https://cloud.githubusercontent.com/assets/8790191/4288182/e8cec4fc-3da9-11e4-98d1-26cc59911338.jpg)
![docket-4](https://cloud.githubusercontent.com/assets/8790191/4288180/e8c427ae-3da9-11e4-8264-85092bfa4730.jpg)
![docket-5](https://cloud.githubusercontent.com/assets/8790191/4288181/e8c5174a-3da9-11e4-8112-b54b1ea81b21.jpg)
![docket-6](https://cloud.githubusercontent.com/assets/8790191/4288184/e8e873e8-3da9-11e4-8fad-dea86d189fa9.jpg)
![docket-7](https://cloud.githubusercontent.com/assets/8790191/4288185/e8eea77c-3da9-11e4-9e72-dfbc1515349f.jpg)
![docket-8](https://cloud.githubusercontent.com/assets/8790191/4288186/e8f19ed2-3da9-11e4-9104-71dfe2fe63c9.jpg)
![docket-9](https://cloud.githubusercontent.com/assets/8790191/4288188/e8f307c2-3da9-11e4-9b16-03f3b6beed0e.jpg)
![docket-10](https://cloud.githubusercontent.com/assets/8790191/4288187/e8f2ddec-3da9-11e4-9622-7f7c4a06959d.jpg)
![docket-11](https://cloud.githubusercontent.com/assets/8790191/4288189/e8f98a8e-3da9-11e4-9394-8b725ae2f9b0.jpg)

**Comment by YairChen** [comment]
Alex\Simon\Avi wait with this task. 
We should make priorities and until then Alex will continue to fix bugs

**Comment by feigale** [comment]
![d3](https://cloud.githubusercontent.com/assets/8790628/4417772/4e1f5e42-4558-11e4-874a-0ac0c52095fc.jpg)
![d1](https://cloud.githubusercontent.com/assets/8790628/4417773/4e21a0b2-4558-11e4-9f06-655ae338500e.jpg)
![d2](https://cloud.githubusercontent.com/assets/8790628/4417774/4e24c396-4558-11e4-9e3c-f41abefc9ea9.jpg)

**Comment by feigale** [comment]
![d11](https://cloud.githubusercontent.com/assets/8790628/4418106/f7faadec-455b-11e4-9e97-bde0b50e057c.jpg)
![d4](https://cloud.githubusercontent.com/assets/8790628/4418107/f7fba904-455b-11e4-9055-d72056a2ea97.jpg)
![d5](https://cloud.githubusercontent.com/assets/8790628/4418108/f81886be-455b-11e4-9081-5008bb685d35.jpg)
![d6](https://cloud.githubusercontent.com/assets/8790628/4418109/f822b65c-455b-11e4-85f4-51b48471cd39.jpg)
![d7](https://cloud.githubusercontent.com/assets/8790628/4418112/f8289cfc-455b-11e4-9e5d-1ba5b4f36276.jpg)
![d8](https://cloud.githubusercontent.com/assets/8790628/4418110/f8248612-455b-11e4-9eb7-076dac2527c5.jpg)
![d9](https://cloud.githubusercontent.com/assets/8790628/4418111/f827cd9a-455b-11e4-8039-3559f87a5c76.jpg)
![d10](https://cloud.githubusercontent.com/assets/8790628/4418113/f84166a6-455b-11e4-9ea2-6997aeeb28b8.jpg)

**Comment by feigale** [comment]
![d10](https://cloud.githubusercontent.com/assets/8790628/4419054/8beba286-4566-11e4-865d-5fbccdb7ab44.jpg)

**Comment by simon-sh** [comment]
Change: (discussed with @YairChen )

When editing an existing order, DO NOT show "client type" related info. Leave it clear..

Where you see on the screenshow "תיירות פנים" should be empty space

![1](https://cloud.githubusercontent.com/assets/8789505/4491539/ba28741c-4a39-11e4-80f7-6342e2f9fba4.PNG)

**Comment by DamirHaibullin** [comment]
Changeset 2379 - resolve https://cloud.githubusercontent.com/assets/8790628/4417772/4e1f5e42-4558-11e4-874a-0ac0c52095fc.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2383 - resolve https://cloud.githubusercontent.com/assets/8790628/4417774/4e24c396-4558-11e4-9e3c-f41abefc9ea9.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2412 - resolve https://cloud.githubusercontent.com/assets/8790191/4288181/e8c5174a-3da9-11e4-8112-b54b1ea81b21.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2418 - resolve https://cloud.githubusercontent.com/assets/8790628/4418106/f7faadec-455b-11e4-9e97-bde0b50e057c.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2419 - resolve https://cloud.githubusercontent.com/assets/8790628/4419054/8beba286-4566-11e4-865d-5fbccdb7ab44.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2424 - resolve https://cloud.githubusercontent.com/assets/8790628/4418111/f827cd9a-455b-11e4-8039-3559f87a5c76.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2427 - resolve https://cloud.githubusercontent.com/assets/8790628/4418110/f8248612-455b-11e4-9eb7-076dac2527c5.jpg and https://cloud.githubusercontent.com/assets/8790628/4418112/f8289cfc-455b-11e4-9e5d-1ba5b4f36276.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2438 - resolve https://cloud.githubusercontent.com/assets/8790628/4418109/f822b65c-455b-11e4-85f4-51b48471cd39.jpg

**Comment by DamirHaibullin** [comment]
Changeset 2453 - resolve https://cloud.githubusercontent.com/assets/8790191/4288183/e8cfb51a-3da9-11e4-82a4-d446a489e3d2.jpg

**Comment by Avi888** [comment]
קובץ תיקונים - Docket

Docket - 01
סעיף 02 - לא תוקן
סעיף 03 - תיקון לא נכון - להתאים את המרחקים כפי שמוצג בעיצוב
סעיף 05 - לא תוקן
סעיף 06 - לא תוקן (יש משמאל לאייקון נקודה שחורה מיותרת)
סעיף 08 - לא תוקן
סעיף 09 - לא תוקן
סעיף 10 - לא תוקן

Docket - 02
סעיף 01 - לא תוקן
סעיף 02 - לא תוקן

Docket - 03
סעיף 01 - לא תוקן
סעיף 02 - לא תוקן
סעיף 03 - לא תוקן

Docket - 04
סעיף 01 - לא תוקן
סעיף 02 - לא תוקן
סעיף 03 - לא תוקן
סעיף 04 - לא תוקן

Docket - 05
כל הסעיפים - לא תוקנו

Docket - 06
כל הסעיפים - לא מוצגים האייקונים לתצוגת טבלאות - אין אפשרות לבדוק

Docket - 07
לא ניתן לבדיקה

Docket - 08
סעיף 01 - לא תוקן
סעיף 02 - הכפתור צ״ל ממוקם 5px מימין, 7px מלמעלה ומלמטה - עד לטבלה)
סעיף 30 - לא תוקן

Docket - 09
כל הסעיפים - לא תוקנו

Docket - 10
כל הסעיפים - לא תוקנו

Docket - 11
כל הסעיפים - לא תוקנו

**Comment by DamirHaibullin** [comment]
Changeset 2460 Docket - 01 סעיף 02 - לא תוקן

**Comment by DamirHaibullin** [comment]
Changeset 2463 - fix count orders of result in order toolbar
