### ISSUE TITLE
Customer Search (Search Screens) 2

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#250]
![customer-search- search-screens -01-1](https://cloud.githubusercontent.com/assets/8790191/5815856/7ddfd1a2-a0a2-11e4-8bdb-855d82f77c1e.jpg)
![customer-search- search-screens -01-2](https://cloud.githubusercontent.com/assets/8790191/5815860/7de8b7a4-a0a2-11e4-8bf7-ec57fc11d5c9.jpg)
![customer-search- search-screens -01-3](https://cloud.githubusercontent.com/assets/8790191/5815858/7de537c8-a0a2-11e4-99be-437f18984dff.jpg)
![customer-search- search-screens -01-4](https://cloud.githubusercontent.com/assets/8790191/5815859/7de59be6-a0a2-11e4-80ab-7174fd566269.jpg)
![customer-search- search-screens -01-5](https://cloud.githubusercontent.com/assets/8790191/5815857/7de29c52-a0a2-11e4-9f3f-06c15cfc865c.jpg)
![customer-search- search-screens -01-6](https://cloud.githubusercontent.com/assets/8790191/5815861/7e0032a8-a0a2-11e4-84ce-da0b10876632.jpg)
![customer-search- search-screens -01-7](https://cloud.githubusercontent.com/assets/8790191/5815862/7e01107e-a0a2-11e4-82ca-24d8b54d8d7f.jpg)
![customer-search- search-screens -02-1](https://cloud.githubusercontent.com/assets/8790191/5815863/7e050a80-a0a2-11e4-8f94-7239d2272196.jpg)
![customer-search- search-screens -02-2](https://cloud.githubusercontent.com/assets/8790191/5815864/7e06e72e-a0a2-11e4-8c54-d319b377a153.jpg)
![customer-search- search-screens -02-3](https://cloud.githubusercontent.com/assets/8790191/5815865/7e088c82-a0a2-11e4-8877-d7a4844c4852.jpg)
![customer-search- search-screens -02-4](https://cloud.githubusercontent.com/assets/8790191/5815868/7e274460-a0a2-11e4-8f56-cd43986c3c66.jpg)
![customer-search- search-screens -02-5](https://cloud.githubusercontent.com/assets/8790191/5815866/7e25bbe0-a0a2-11e4-8ab2-1f742410b231.jpg)
![customer-search- search-screens -02-6](https://cloud.githubusercontent.com/assets/8790191/5815869/7e27480c-a0a2-11e4-9fb2-344e117bae4a.jpg)
![customer-search- search-screens -02-7](https://cloud.githubusercontent.com/assets/8790191/5815867/7e26e0ba-a0a2-11e4-8e62-fa54cae09fc5.jpg)
![customer-search- search-screens -02-8](https://cloud.githubusercontent.com/assets/8790191/5815870/7e27affe-a0a2-11e4-8856-86e5d8c95d0e.jpg)
![customer-search- search-screens -03-1](https://cloud.githubusercontent.com/assets/8790191/5815871/7e4761aa-a0a2-11e4-9d91-42c200b6e6a6.jpg)

**Comment by Avi888** [comment]
PSD file sent via email to anton & tanya

**Comment by feigale** [comment]
![customer-search- search-screens -02-1](https://cloud.githubusercontent.com/assets/8790628/5833381/0ddfbe90-a17d-11e4-84e2-7aff52c5de94.jpg)
![customer-search- search-screens -02-2](https://cloud.githubusercontent.com/assets/8790628/5833382/0e0e4ce2-a17d-11e4-8b94-8fec2bb11347.jpg)
![customer-search- search-screens -02-3](https://cloud.githubusercontent.com/assets/8790628/5833387/0e1a015e-a17d-11e4-8f8b-2b0665edeedc.jpg)
![customer-search- search-screens -02-4](https://cloud.githubusercontent.com/assets/8790628/5833385/0e19984a-a17d-11e4-8a0c-4036647094fe.jpg)
![customer-search- search-screens -02-5](https://cloud.githubusercontent.com/assets/8790628/5833384/0e18b718-a17d-11e4-8ae6-aa76436d7e3c.jpg)
![customer-search- search-screens -02-6](https://cloud.githubusercontent.com/assets/8790628/5833386/0e19a34e-a17d-11e4-80bb-af444f751b33.jpg)
![customer-search- search-screens -02-7](https://cloud.githubusercontent.com/assets/8790628/5833383/0e170b2a-a17d-11e4-8f19-055b2a2ad02b.jpg)
![customer-search- search-screens -02-8](https://cloud.githubusercontent.com/assets/8790628/5833389/0e418b0c-a17d-11e4-8b40-319a870a6971.jpg)
![customer-search- search-screens -03-1](https://cloud.githubusercontent.com/assets/8790628/5833388/0e40f89a-a17d-11e4-8c16-4be3baf3b6cd.jpg)
![customer-search- search-screens -01-1](https://cloud.githubusercontent.com/assets/8790628/5833391/0e46a1d2-a17d-11e4-8607-723f581527d2.jpg)
![customer-search- search-screens -01-2](https://cloud.githubusercontent.com/assets/8790628/5833390/0e4563d0-a17d-11e4-95b8-27c76872d0ea.jpg)
![customer-search- search-screens -01-3](https://cloud.githubusercontent.com/assets/8790628/5833392/0e477968-a17d-11e4-9902-0cd89aca6c02.jpg)
![customer-search- search-screens -01-4](https://cloud.githubusercontent.com/assets/8790628/5833393/0e5e72a8-a17d-11e4-80a8-7ab71d2b1846.jpg)
![customer-search- search-screens -01-5](https://cloud.githubusercontent.com/assets/8790628/5833394/0e684a3a-a17d-11e4-8042-62abc32771e8.jpg)
![customer-search- search-screens -01-6](https://cloud.githubusercontent.com/assets/8790628/5833395/0e69c8b0-a17d-11e4-9d09-c9049b620c22.jpg)
![customer-search- search-screens -01-7](https://cloud.githubusercontent.com/assets/8790628/5833396/0e6c4f22-a17d-11e4-990d-abcb1a1ef35f.jpg)

**Comment by AlexSin15** [comment]
Changeset 3030
