### ISSUE TITLE
Bussines Customer Search (Menu)

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#253]
![bussines-customer-search- menu](https://cloud.githubusercontent.com/assets/8790191/5854080/bf72e21c-a232-11e4-8e17-8b2f42546d39.jpg)

**Comment by Avi888** [comment]
PSD file sent via email to tanya & anton

**Comment by AlexSin15** [comment]
![-2](https://cloud.githubusercontent.com/assets/8788242/5873237/8557356e-a31e-11e4-9eaa-e34108693832.jpg)

What should be the logic of these filters?
