### ISSUE TITLE
search order- filter 

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#255]
1.search order by date
2.click search
3.delete date 
4.search by order no. 183

problem
no get this order because it stiil filter by date too

![1](https://cloud.githubusercontent.com/assets/8806064/5856872/8e484e12-a24f-11e4-8c71-64e60fbaab12.PNG)

![2](https://cloud.githubusercontent.com/assets/8806064/5856873/90a32f06-a24f-11e4-96ec-fe7c47e4e603.PNG)

![3](https://cloud.githubusercontent.com/assets/8806064/5856877/9d0087da-a24f-11e4-9715-0263373df83a.PNG)

**Comment by DamirHaibullin** [comment]
Changeset 3057
