### ISSUE TITLE
search order- filter by status multiselect

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#256]
1.click multiselect filter by status
2.click select all - all status selected 
problem 
just if i click on status is filtered by select

3.after i click on all status 
i want to delete 1 status
clicked again on status  is delete 2 status

1.
![1](https://cloud.githubusercontent.com/assets/8806064/5857477/d890ab2c-a254-11e4-81c8-4a5605c5c318.PNG)

2.
![2](https://cloud.githubusercontent.com/assets/8806064/5857478/dd30a8bc-a254-11e4-9d6f-45866d249287.PNG)

3.
![3](https://cloud.githubusercontent.com/assets/8806064/5857481/dfc8d2b6-a254-11e4-9d20-f51fb1711c02.PNG)

**Comment by yosi-yaya** [comment]
this bug is all multiselect in search order filter
1. by employee
2.by branch
3.by status
4. by curency

**Comment by AlexSin15** [comment]
Changeset 3062

**Comment by novice3030** [comment]
@yosi-yaya please check it and close the issue if it's fixed
