### ISSUE TITLE
search flight not work 

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#257]
![1](https://cloud.githubusercontent.com/assets/8806064/5857909/e5eda56a-a257-11e4-8720-fc023487d958.PNG)

**Comment by DamirHaibullin** [comment]
Error " Localization key not found in dictionary:TLV > ETH 25-29/1/15 " is this not error, it's warning.

Thе Problem was not the correct data in Provider Product table for Provider(id:11, name: ארקיע). The provider was in search filter select option _ספקים_.
_Solution_.
- I have opened Provider Card by Provider Id=11
- Open tab _מוצרים / הסכמים_
- Add or Edit  row.
- In Opened PopUp need select for 
  - סוג מוצר(ProductType) -  טיסות(Flight)
  - מוצר(Product) - ארקיע
  - סוג עיסקה(OrderClientType) - Domestic
- Save change

**Comment by DamirHaibullin** [comment]
![searchflights](https://cloud.githubusercontent.com/assets/6190927/5870709/e8c94302-a2fc-11e4-84a8-f401ac5af125.png)
