### ISSUE TITLE
when opening voucher popup in docket the dockect hasChanges state is changed

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#258]
1.  open docket 1882
2. open the voucher from accounting tab
3. we didn't change anything but still docket has changes

![image](https://cloud.githubusercontent.com/assets/6697179/5891737/247b4d48-a4ae-11e4-9b23-7249c5420d0e.png)

**Comment by DamirHaibullin** [comment]
For this situation when open the voucher popUp in VoucherPopUpController call function _init()_. In this function line(964) calling function _updateTotalVCHR(totalVCHRAmount)_. In this function we have next codes: 
_$scope.order.SaleAccountingInfo.TotalVCHR += amount;_
_$scope.order.CostAccountingInfo.TotalVCHR += amount;_
The $scope.order is breeze object then we saw state - _changed_ in docket.

**Comment by novice3030** [comment]
Good find @damir26 
This bug is actually should be fixed be me.
To fix this I think we should move that logic to the server side when creating the voucher.
After we come back from the server  with success we should make sure that the client side entities are also updated with the correct data

**Comment by novice3030** [comment]
I resolved but still didn't commit or closed because more testing should be made
