### ISSUE TITLE
Flight Service Refresh button - multiply the customers on each pressing

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#26]
1. I add a flight result to a new sum
2. In service customer it show 2 pax
3. I press the Refresh button 
4. the refresh double the customer so now it became 4 customer
5. I press again and the customer became 6 pax 
6. and so on...
   ![1](https://cloud.githubusercontent.com/assets/7251658/4290731/57c15b5e-3dbe-11e4-9ccb-c1b67b2e64fd.JPG)

**Comment by suhrab** [comment]
Changeset 2253
