### ISSUE TITLE
balance in RMT - PPC screen when joining provider invoice 

### ISSUE THREAD

**Issue by rrredshay** [yayasoft/ytour#267]
amount is the net, its mean that the additions count twice! 

EXMP:
bruto 1000
net 800
=========>
amount 800 ------> should be 1000
balance 600 ------>  should be 800

**Comment by YairChen** [comment]
שי,

לא הבנתי מה הסברת פה.

תסביר לי.

  file:///C:UsersYayaAppDataRoamingMicrosoftSignaturesyayasoftlogo.gif 

יאיר חן - Yair Chen

מנכ"ל - CEO

טלפון / Phone:

03-5787772

פקס / Fax:

03-5700549

נייד / Mobile:

052-2740278

דוא"ל / E-mail:

 mailto:yaya@yayasoft.co.il yaya@yayasoft.co.il

אינטרנט / Internet:

 http://www.yayasoft.co.il/ http://www.yayasoft.co.il
http://www.hotelligence.co.il http://www.hotelligence.co.il/

**Comment by rrredshay** [comment]
היתה בעייה בחישוב של חשבונית ספק בRMT.
העמלה קוזזה פעמיים
