### ISSUE TITLE
filter search customer-in result the button select not work

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#269]
1. click on filter search customer
2. in result click on button select

problem

not select it

![1](https://cloud.githubusercontent.com/assets/8806064/6019624/3d493ebc-abab-11e4-9161-8bc0c8b2f098.PNG)

![2](https://cloud.githubusercontent.com/assets/8806064/6019626/4148b484-abab-11e4-9aa1-96972d14d528.PNG)

**Comment by AlexSin15** [comment]
Changeset 3112
