### ISSUE TITLE
Service Flight - commission field in pax calc in wrong way

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#27]
1. I add a flight service from search to a new sum
2. I expand the customer section in the service
3. I tried to input "10" as commission in the text box 
4. after I key the "1" digit, the field recalc itself and show "0.98"
   5.I tried to key "2" and it became "2.04"
5. and so on...
   ![1](https://cloud.githubusercontent.com/assets/7251658/4290820/0609908c-3dbf-11e4-9eeb-be94b9da8590.JPG)

**Comment by simon-sh** [comment]
I have an ugly fix for this bug, W'ONT commit it....
Waiting for @novice3030 to refactor code

**Comment by novice3030** [comment]
@yayasoft-simon I don't think you should wait for me it might take me sometime to finish and i rather work from something that has all the functionality rather then redoing the same bugs over again

**Comment by YairChen** [comment]
Ran, I don't want this ugly fix. Make an effort and make refactoring to this also or give Simon alternativ which better than this fix.

**Comment by suhrab** [comment]
Money type library for javascript should be used to do calculations. Like https://github.com/MikeMcl/bignumber.js

.round(2) only for UI

pure javascript has only float type.

console.log( 0.1 + 0.2 ); // 0.30000000000000004
console.log((877.2342342).round(2)); // 877.23
(877.23555).round(2); // 877.24

**Comment by novice3030** [comment]
I removed the .round(2) from calcs it should only be used for view not for the model value
