### ISSUE TITLE
flight service- extra commision not calc

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#271]
1.add flight service in order
2.in price input 1000 bruto and commision 100
3.in extra commision input set 10%

problem

not calc extra commision 
total neto price =900
the total neto price correct is 800

![1](https://cloud.githubusercontent.com/assets/8806064/6103185/d38959be-b049-11e4-9a20-978153d8eb8e.PNG)

**Comment by AlexSin15** [comment]
Changeset 3150
