### ISSUE TITLE
provider card - product type needs to have default value

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#273]
when creating a new agreeent the defualt productt type should be hotel

![image](https://cloud.githubusercontent.com/assets/6697179/6211897/b6cb7f98-b5e7-11e4-821e-341c1a971093.png)

**Comment by samat89** [comment]
Not only ProductType, but also some data will be changed as default, because optional data(checkBox, radio) are depend on type

**Comment by samat89** [comment]
Changeset 3190

**Comment by novice3030** [comment]
seems to be ok
