### ISSUE TITLE
flight search filter

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#280]
1.search flight-get resault sapak arkia
2.open filter
3.filter by arkia

problem 

delete all resault for arkia

![1](https://cloud.githubusercontent.com/assets/8806064/6244257/7c445354-b759-11e4-85ea-a478b98077d9.PNG)

![2](https://cloud.githubusercontent.com/assets/8806064/6244258/7e5a4a90-b759-11e4-8f3c-5be2dbd3f3e1.PNG)

**Comment by web4social** [comment]
@yosi-yaya This is filter by Suppliers not by Airlines. In this flights airline arkia, but orderFromProvider another
