### ISSUE TITLE
Docket - Clicking on accounting info tab more then one time results in duplicated rows in the grid

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#281]
When clicking on the accounting document tab in the docket it adds a duplicated row in the accounting grid.

@suhrab please talk to me first before resolving this bug I want to make sure you implemented the correct logic in order to refresh the grid

![image](https://cloud.githubusercontent.com/assets/6697179/6244487/dc094f80-b75c-11e4-85e5-be4bc997700b.png)

**Comment by DamirHaibullin** [comment]
Changeset 3198

**Comment by novice3030** [comment]
seems to be fixed
