### ISSUE TITLE
ppc-add voucher to provider invoice

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#286]
1.add voucher to invoice
2. in invoice i change the curenncy to $
3. click in create-success

problem

the curenncy invoice must be same curenncy voucher

dont have to set it

![1](https://cloud.githubusercontent.com/assets/8806064/6348658/74f8cfd2-bc2a-11e4-9d7b-89293d38ec80.PNG)

**Comment by novice3030** [comment]
currency shouldn't be editiable. we should change it to read only

**Comment by novice3030** [comment]
I've changed it to read only
@yosi-yaya  please check and close if it's fixed
