### ISSUE TITLE
ppc-add provider invoice

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#287]
1.add voucher to provider invoice 
2.add number provider
3.add date invoice as the date has already passed
4.click on create

problem
the date change to date of today
Should be allowed to set the date has already been

![1](https://cloud.githubusercontent.com/assets/8806064/6349376/6d891bb4-bc32-11e4-968d-07a70ae4bac0.PNG)

**Comment by simon-sh** [comment]
BaseAccountingDocument::BeforeSaveEntity
Fix overriding IssueDate with default value
