### ISSUE TITLE
ppc-add voucher to batch

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#288]
1.add 2 vouchers to batch
2.after add same 2 vouchers to another batch

Is this behavior is ok or not?

![1](https://cloud.githubusercontent.com/assets/8806064/6350042/f2f5a960-bc38-11e4-8afa-98d5083faf9e.PNG)

**Comment by simon-sh** [comment]
Fix description:
New 'Unique' index in the table BatchDocuments (UNIQUE_DocumentId)
