### ISSUE TITLE
Funds screen

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#292]
PSD file and all the JPG files sent by email to Tanya

**Comment by feigale** [comment]
![accountancyscreens-06-1](https://cloud.githubusercontent.com/assets/8790628/6386249/82804bc2-bda0-11e4-9400-aa0f44f4c367.jpg)
![accountancyscreens-06-2](https://cloud.githubusercontent.com/assets/8790628/6386251/828b64ee-bda0-11e4-823c-5bf71f28cef6.jpg)
![accountancyscreens-06-3](https://cloud.githubusercontent.com/assets/8790628/6386250/8289f834-bda0-11e4-88f9-c9657d74a41d.jpg)
![accountancyscreens-06-4](https://cloud.githubusercontent.com/assets/8790628/6386252/828fae82-bda0-11e4-8e86-5e1304145dd3.jpg)
![accountancyscreens-06-5](https://cloud.githubusercontent.com/assets/8790628/6386253/82904c70-bda0-11e4-92fd-f8c8274034f5.jpg)
![accountancyscreens-01-1](https://cloud.githubusercontent.com/assets/8790628/6386254/8295a65c-bda0-11e4-9bef-66811ff3bbc9.jpg)
![accountancyscreens-01-2](https://cloud.githubusercontent.com/assets/8790628/6386255/82a7f370-bda0-11e4-9d65-5a2995a23e07.jpg)
![accountancyscreens-02-1](https://cloud.githubusercontent.com/assets/8790628/6386256/82b4a6ba-bda0-11e4-81bd-c0b56ae7d29f.jpg)
![accountancyscreens-02-2](https://cloud.githubusercontent.com/assets/8790628/6386257/82b6a1fe-bda0-11e4-9dc5-4a1ec7e504df.jpg)
![accountancyscreens-02-3](https://cloud.githubusercontent.com/assets/8790628/6386259/82b9aeb2-bda0-11e4-93e9-336203aef58e.jpg)
![accountancyscreens-03-1](https://cloud.githubusercontent.com/assets/8790628/6386258/82b96542-bda0-11e4-9856-a90236034656.jpg)
![accountancyscreens-03-2](https://cloud.githubusercontent.com/assets/8790628/6386260/82bd970c-bda0-11e4-8c56-de3f79ab6379.jpg)
![accountancyscreens-03-3](https://cloud.githubusercontent.com/assets/8790628/6386261/82cd886a-bda0-11e4-8676-c736c93ddbc5.jpg)
![accountancyscreens-03-4](https://cloud.githubusercontent.com/assets/8790628/6386262/82db5b34-bda0-11e4-9b22-7a89f4124c58.jpg)
![accountancyscreens-04-1](https://cloud.githubusercontent.com/assets/8790628/6386263/82de5c26-bda0-11e4-9c37-ff721689deda.jpg)
![accountancyscreens-04-2](https://cloud.githubusercontent.com/assets/8790628/6386264/82e3213e-bda0-11e4-957f-5670dff3c1e7.jpg)
![accountancyscreens-04-3](https://cloud.githubusercontent.com/assets/8790628/6386265/82e3e2a4-bda0-11e4-916c-de50f5e75c5e.jpg)
![accountancyscreens-04-4](https://cloud.githubusercontent.com/assets/8790628/6386266/82e4eb4a-bda0-11e4-89d6-aa4122e45202.jpg)
![accountancyscreens-04-5](https://cloud.githubusercontent.com/assets/8790628/6386267/82f432b2-bda0-11e4-83ca-d56f33da4c7d.jpg)
![accountancyscreens-04-6](https://cloud.githubusercontent.com/assets/8790628/6386269/83052f36-bda0-11e4-9815-027e910b7936.jpg)
![accountancyscreens-05-1](https://cloud.githubusercontent.com/assets/8790628/6386268/8305269e-bda0-11e4-8225-64f531496a9b.jpg)
![accountancyscreens-05-2](https://cloud.githubusercontent.com/assets/8790628/6386270/830a0006-bda0-11e4-9b41-dd97f5977cb8.jpg)
![accountancyscreens-05-3](https://cloud.githubusercontent.com/assets/8790628/6386272/830e06ec-bda0-11e4-8bf1-b8cf8ea021e5.jpg)
![accountancyscreens-05-4](https://cloud.githubusercontent.com/assets/8790628/6386271/830b65d6-bda0-11e4-8152-ea56a7384f10.jpg)
![accountancyscreens-05-5](https://cloud.githubusercontent.com/assets/8790628/6386273/831b0a90-bda0-11e4-9a45-22d3c8589e6b.jpg)

**Comment by samat89** [comment]
Height of footer cannot be constant(e.g, 42px), because it depends on count of currencies. How many currencies we have, the height of footer will be raised.

**Comment by samat89** [comment]
Excessive white background in footer is linked with the ui-grid
http://jira.logi-sense.com/browse/YT-115
Will be solved there, in stable version

**Comment by samat89** [comment]
Changeset 3226

**Comment by samat89** [comment]
Creating new popups for editing payments will be solved as task in https://github.com/yayasoft/ytour/issues/293

**Comment by Avi888** [comment]
Some issues remain related to UI grid...
