### ISSUE TITLE
Credit Card Screen

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#295]
![creditcard-screen-04](https://cloud.githubusercontent.com/assets/8790191/6430256/c916af6a-c00a-11e4-9238-bcfdb486df6d.jpg)
![creditcard-screen-03](https://cloud.githubusercontent.com/assets/8790191/6430259/c91b4692-c00a-11e4-8722-a5d11fef43cc.jpg)
![creditcard-screen-02](https://cloud.githubusercontent.com/assets/8790191/6430257/c91a1448-c00a-11e4-8db3-8d10702dc531.jpg)
![creditcard-screen-01](https://cloud.githubusercontent.com/assets/8790191/6430260/c9a03618-c00a-11e4-9fda-3a989a51aac9.jpg)
![creditcard-screen-05](https://cloud.githubusercontent.com/assets/8790191/6430258/c91b1da2-c00a-11e4-89ff-f79983c3be5e.jpg)

**Comment by feigale** [comment]
1. Расстояния между разделительными линиями не одинаковые - должны быть 35 пикс.
2. Фон, который показывает выделение, должен закрывать разделительные линии - 37 пикс.
3. Не хватает вкладки "Привязанные квитанции"
4. Текст и стрелочка внутри текстбокса "номер счета для вклада" расположен слишком высоко и смещен влево
5. Не хватает тени

**Comment by samat89** [comment]
About 3 point. This tab is not necessary now.
There is no spec on that tab.

**Comment by samat89** [comment]
Changeset 3251
