### ISSUE TITLE
Income Card Screen

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#296]
![incomecard-screen-02-2](https://cloud.githubusercontent.com/assets/8790191/6430382/4fd5461a-c010-11e4-921e-5538a4781a4d.jpg)
![incomecard-screen-01-1](https://cloud.githubusercontent.com/assets/8790191/6430385/4fd707c0-c010-11e4-92c6-e4d2d3ca5e80.jpg)
![incomecard-screen-02-3](https://cloud.githubusercontent.com/assets/8790191/6430383/4fd594a8-c010-11e4-83a0-ad338b89e8d4.jpg)
![incomecard-screen-02-1](https://cloud.githubusercontent.com/assets/8790191/6430384/4fd5a7ea-c010-11e4-944f-469fc3417b3f.jpg)

**Comment by feigale** [comment]
![4fd5a7ea-c010-11e4-944f-469fc3417b3f](https://cloud.githubusercontent.com/assets/8790628/6437235/d943772a-c0e5-11e4-8823-44a746b4b8fd.jpg)
![4fd594a8-c010-11e4-83a0-ad338b89e8d4](https://cloud.githubusercontent.com/assets/8790628/6437237/d94510bc-c0e5-11e4-8d61-b9ad31b7e550.jpg)
![4fd707c0-c010-11e4-92c6-e4d2d3ca5e80](https://cloud.githubusercontent.com/assets/8790628/6437236/d944582a-c0e5-11e4-8fa1-84a6bf1bc1a4.jpg)
![4fd5461a-c010-11e4-921e-5538a4781a4d](https://cloud.githubusercontent.com/assets/8790628/6437234/d9432d2e-c0e5-11e4-825a-f0fe5da33355.jpg)

**Comment by AlexSin15** [comment]
Changeset 3254

**Comment by AlexSin15** [comment]
About 3 point. Need design of PopUp.

**Comment by Avi888** [comment]
Shows normal 'Receipt' PopUp

![receipt-01](https://cloud.githubusercontent.com/assets/8790191/6461363/dd565e96-c1a7-11e4-95aa-3cdcb40a6c18.jpg)

**Comment by AlexSin15** [comment]
Where in the system I can call and see it?

**Comment by itzik182** [comment]
@suhrab 
Open document popup:
1. Add to your controller the service: "accountingDocumentsDialogs".
2. Add  this function to your controller:
   $scope.showDocument = function (selectedDoc) {
           var params = {
               openType: null, // Required only for DCCD
               openFrom: "revenuesCard", // Required only for DCCD
               isDisplayVat: false, // Required only for DCCD
               cardId: $scope.preOrder.Id, // Required only for DCCD
               documentId: selectedDoc.BaseAccountingDocumentId, // Required
               documentTypeName: selectedDoc.DocumentType.DocumentName, // Required
           }
           accountingDocumentsDialogs.showDocument(params).then(function (result) {
               if (result)
       {
            // your logic...
                   //refreshAccoutingGrid();
       {
           });
       }
3. Call this function from ui in the ng-click event on the document number and send to function this document.

**Comment by AlexSin15** [comment]
Changeset 3266
