### ISSUE TITLE
Expenses Card Screen

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#297]
![expenses-card-screen](https://cloud.githubusercontent.com/assets/8790191/6430420/2bac0bbe-c012-11e4-9b3f-03a108fa6403.jpg)

**Comment by feigale** [comment]
1. Вместо слова доходы нужно расходы הוצאות
2. Комментарии относительно рамочек и общего фона - см. экран кредитных карт и revenue card

**Comment by AlexSin15** [comment]
Changeset 3247
