### ISSUE TITLE
Bank Accounts Screen

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#298]
![bank-accounts-screen-03](https://cloud.githubusercontent.com/assets/8790191/6430525/9bb8d87a-c016-11e4-8511-19ebf70349b2.jpg)
![bank-accounts-screen-02](https://cloud.githubusercontent.com/assets/8790191/6430526/9c0755f4-c016-11e4-8ebc-37e56cdfb29f.jpg)
![bank-accounts-screen-01](https://cloud.githubusercontent.com/assets/8790191/6430527/9c078204-c016-11e4-8da9-27533fa41d54.jpg)

**Comment by feigale** [comment]
![9bb8d87a-c016-11e4-8511-19ebf70349b2](https://cloud.githubusercontent.com/assets/8790628/6437429/ec4ee61c-c0e8-11e4-80a1-0e4c09fef3ad.jpg)
![9c0755f4-c016-11e4-8ebc-37e56cdfb29f](https://cloud.githubusercontent.com/assets/8790628/6437431/ec50e49e-c0e8-11e4-920a-124e523f18a8.jpg)
![9c078204-c016-11e4-8da9-27533fa41d54](https://cloud.githubusercontent.com/assets/8790628/6437430/ec4f1ab0-c0e8-11e4-83cc-bb420a110e15.jpg)

**Comment by AlexSin15** [comment]
About 3 point Yair said, it is not necessary

**Comment by Avi888** [comment]
If Yair said, Who am I ...

**Comment by AlexSin15** [comment]
Сan you discuss it with him?
If you decide to make it, I will do it.

**Comment by AlexSin15** [comment]
Changeset 3237

**Comment by YairChen** [comment]
Alex, which 3 points you talking about?

**Comment by AlexSin15** [comment]
About first screen
![123123](https://cloud.githubusercontent.com/assets/8788242/6457436/f387cc20-c19f-11e4-8dcd-4a4bb8afb205.jpg)

**Comment by 101SYS** [comment]
Hi Alex
the block is mandatory, the fields are optional (can have empty values)

**Comment by AlexSin15** [comment]
Ok

**Comment by AlexSin15** [comment]
Changeset 3269
