### ISSUE TITLE
update details customer

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#301]
1. add customer from list customer to order

2.update id for customer

3.click save

problem 

not save details have error

if new customer its ok

![1](https://cloud.githubusercontent.com/assets/8806064/6438278/433ee5b2-c0d0-11e4-8399-9878da82be40.PNG)

**Comment by AlexSin15** [comment]
Changeset 3243

**Comment by novice3030** [comment]
this is not a bug it has to do with old customer that doesn't have the address object
I resolved it by changing AddressId to be nullable
