### ISSUE TITLE
Empty hotel name when editing existing product

### ISSUE THREAD

**Issue by suhrab** [yayasoft/ytour#309]
Providers. Product tab. Edit product.
Product name(Hotel name) was empty.
Logged with user eshet.

**Comment by web4social** [comment]
**BreezeApiController**
method **Hotels** is used to get hotel by id, it checks if hotel agency id and current user agency id are equal.
**AutoCompleteHotel** do not have validation for agency id, grabs all hotels

So we should add a check for agency id in AutoCompleteHotel method.
When creating new product, **AutoCompleteHotel** is used, thats why we have successfully created new product type with user **eshet**, though eshet's agency does not have Hotels at all
@novice3030

**Comment by novice3030** [comment]
@web4social you are right it seems that right now agency 26 (eseht) doesn't have hotels in the DB
I will fix this now and let you know when it's done

**Comment by novice3030** [comment]
@web4social  agency 26 now has all hotelligence hotels
