### ISSUE TITLE
Order tbl - Quote number not shown

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#35]
After I choose a qoute from the order search screen, I click on its number and the sum screen appears with this quote but the title is "New order".
Shoul be "Quote number ..."

Repro steps:

1) Click on order management
2) Click on order

![1](https://cloud.githubusercontent.com/assets/8789505/4316853/0bd23606-3f0c-11e4-8c8a-5aed5df04519.PNG)

"New order" caption already fixed, it's shows "Quote number ...", but the quote number is far away from 
the label. Make the gap between the "Quote number" and the number as 1-2 spaces

![2](https://cloud.githubusercontent.com/assets/8789505/4317226/c49f11be-3f10-11e4-9bee-25204d9f96d1.PNG)

![Uploading 2.PNG . . .]()

**Comment by web4social** [comment]
fixed
