### ISSUE TITLE
Sum currency convert - wrong calculation

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#38]
![1](https://cloud.githubusercontent.com/assets/7251658/4291897/8854c4b8-3dc8-11e4-9281-3adffad483b5.JPG)
![2](https://cloud.githubusercontent.com/assets/7251658/4291898/8a4a0800-3dc8-11e4-933f-e26f529702da.jpg)
![3](https://cloud.githubusercontent.com/assets/7251658/4291900/8bf27a48-3dc8-11e4-80de-84d69fdcee16.JPG)
![4](https://cloud.githubusercontent.com/assets/7251658/4291901/8d8bf6ea-3dc8-11e4-8a82-52c3fa200451.JPG)
![5](https://cloud.githubusercontent.com/assets/7251658/4291925/b0b01ebc-3dc8-11e4-9158-737c428c1ff5.JPG)

**Comment by AlexSin15** [comment]
Changeset 2324

**Comment by novice3030** [comment]
I had to revert change set 2323
Please try and search hotel services with this commit and you'll see the bug.
Why didn't you check if the search is not broken before commiting ?!

**Comment by AlexSin15** [comment]
Need to clean the Local Storage
