### ISSUE TITLE
Search Result discount calculation error

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#39]
Thid result has a discount from the external interface.
But when I open the "Edit result" popup, there is no corellation between s the numbers...
After I press the "Update price" button in the popup, the system "take" the price (1929
![1](https://cloud.githubusercontent.com/assets/7251658/4292152/cf66d79a-3dca-11e4-8031-400a93e5984e.png)
) which is after the discount and show it in the grid like it was the price b4 the dicount!
and also recalculate again the discount from this price (1827)

**Comment by novice3030** [comment]
Yair please take latest and check if it's ok.
if everything is ok please close this issue

**Comment by YairChen** [comment]
It dosn't work.
Try it yourself and fix it.
