### ISSUE TITLE
date of birth textbox is not cleared

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#4]
when adding a new customer from customers popup under the order module and a previous customer was already added the date of birth text box is not cleared

this might be due to the fact that the directive is not using a $watch on the model value

![image](https://cloud.githubusercontent.com/assets/6697179/4275784/785e25aa-3cff-11e4-99df-06bd2465856a.png)

**Comment by AlexSin15** [comment]
Done. Please check.

**Comment by simon-sh** [comment]
resolved in issue 13
