### ISSUE TITLE
calender errors when selecting one way flight in service search

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#40]
when selecting one way flight in service search the calender blocks out dates, dates should be opened from today forward and the text box is not in line with the design

![image](https://cloud.githubusercontent.com/assets/6697179/4292589/b23ae590-3dce-11e4-93cd-4e1cb6ca57f6.png)

![image](https://cloud.githubusercontent.com/assets/6697179/4292616/f2343fd4-3dce-11e4-9615-05a2802e2627.png)

**Comment by web4social** [comment]
I fixed the problem with date.
Avi please send design for flight search, when flight one way
![screenshot_1](https://cloud.githubusercontent.com/assets/8788244/4298644/e30ed8f8-3e27-11e4-8fdc-8ca58e1e2a3e.png)

**Comment by YairChen** [comment]
Avi will send you instructions in the next 30 min.

**Comment by Avi888** [comment]
On 17 בספט 2014, at 08:20, YairChen notifications@github.com wrote:

> Avi will send you instructions in the next 30 min.
> 
> —
> Reply to this email directly or view it on GitHub.

אבי ירמלובסקי Avi Yarmalovski
UI

טלפוןPhone/ :
03-5787772
פקס/Fax :
03-5700549

דוא"לE-mail/ :
aviy@yayasoft.co.ii
אינטרנטInternet/ :
http://www.yayasoft.co.il
http://www.hotelligence.co.il
