### ISSUE TITLE
Search results grid - show only few rows in Table mode

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#42]
There is 3 mode of the hotel results grid presentation:
![3](https://cloud.githubusercontent.com/assets/7251658/4298803/f2f18b90-3e2b-11e4-8e6d-8d1fd27a4569.JPG)
the left one is Grid with Blocks" mode 
the middle is "Grid Only"
the right one is not active right now.

I login as a user "eshet", serach and got a lot of results.
The current mode is grid+blocks:
![1](https://cloud.githubusercontent.com/assets/7251658/4298818/385ed7aa-3e2c-11e4-8ae2-345c8c4bde48.png)

after that I want to switch to "Grid Only" mode.
Then, the grid show only few results and hide all the rest.
![2](https://cloud.githubusercontent.com/assets/7251658/4298833/69a3f002-3e2c-11e4-81a9-d88a69770a3d.JPG)

**Comment by web4social** [comment]
solved changeset 2251
