### ISSUE TITLE
z-validate

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#46]
![z-validate](https://cloud.githubusercontent.com/assets/8790191/4299232/9265b834-3e33-11e4-9c92-b1ac8715bc92.jpg)
In addition to sending a PSD file by e-mail

**Comment by rem4ik4ever** [comment]
Changeset 2250 

Design fixes to z-validate in breeze.directives.js and css

**Comment by rem4ik4ever** [comment]
Changeset 2263 

Fixed for required fields and non required fields. 

@novice3030 also noticed that if page is refreshed all required properties disapear and fields are not marked as required anymore. We might need to create another issue? or is this right behavior?
