### ISSUE TITLE
Another docket screen repair

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#49]
![docket-2](https://cloud.githubusercontent.com/assets/8790191/4301139/fa5bb610-3e4b-11e4-8223-71653f6befa4.jpg)

In addition, sending PSD file by e-mail

**Comment by feigale** [comment]
![docket](https://cloud.githubusercontent.com/assets/8790628/4319779/f02c2202-3f30-11e4-8af4-c8d863ab2812.jpg)
