### ISSUE TITLE
PNR is not being displayed in order view

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#5]
the PNR for each service should always be displayed in order inforamtion tab under the service.
usally it is readonly except in manual service in existing docket (not in quote)

![image](https://cloud.githubusercontent.com/assets/6697179/4283917/a86a0ea0-3d75-11e4-9362-56dfded67d43.png)

**Comment by novice3030** [comment]
after we do booking we no longer have a temp PNR and we should get a real PNR
there for when service is booked don't display the word זמני (temp)

**Comment by suhrab** [comment]
I did booking of online service. ProviderPNR is still empty after successful booking.
Checked database. dbo.ServiceBase, OrderId=14194, PrvoderPNR is empty

**Comment by novice3030** [comment]
try it again and see what happens in booking, do a debug session

**Comment by suhrab** [comment]
ProviderPNR also is not saved after booking offline service. Though hotelligense returns not empty PNR
Working on it...

**Comment by YairChen** [comment]
Offline services do not make book in Hotelligence.
Thehe PNR will be inserted manually by the user.

**Comment by YairChen** [comment]
Anton,
You need also to put PNR field in each room!
It was in the design so ask Roman why they didn't do that.

![docket-hotels](https://cloud.githubusercontent.com/assets/7251658/4318924/ff36a3c8-3f24-11e4-844f-648a5c3075e4.jpg)

**Comment by suhrab** [comment]
Changeset 2272
