### ISSUE TITLE
Packages search results Corrections

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#50]
![packages-search-results-corrections-01](https://cloud.githubusercontent.com/assets/8790191/4302036/9d6f1320-3e55-11e4-83ca-53a0be9dac89.jpg)
![packages-search-results-corrections-02](https://cloud.githubusercontent.com/assets/8790191/4302037/9d758746-3e55-11e4-91ae-0cd88a18b37b.jpg)

**Comment by feigale** [comment]
![packages](https://cloud.githubusercontent.com/assets/8790628/4319716/50c62686-3f30-11e4-9282-6c6f3821d612.jpg)
![packages2](https://cloud.githubusercontent.com/assets/8790628/4319717/50c7a3da-3f30-11e4-9806-e9e352f92a63.jpg)

**Comment by AlexSin15** [comment]
Changeset 2299
