### ISSUE TITLE
Order screen -> wrong placeholder text for "note to provider" input

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#51]
Repro steps:

1) Do the search for hotel
2) Add any hotel to the the order, and open it
3) Click the link "Add note to the hotel"
![1](https://cloud.githubusercontent.com/assets/8789505/4304031/36e2a488-3e6d-11e4-98de-afa519821a05.PNG)

Problem:

The placeholder says "note to the airline company" (Heb: הערה לחב' תעופה )

![2](https://cloud.githubusercontent.com/assets/8789505/4304158/45d45ddc-3e6e-11e4-8aaf-f1878f1c8ded.PNG)

Todo:
1)  Replace the placehoder with text: "Note to provider" (Heb: הערה לספק)
2)  Replace link anchor "Add note to hotel" with "Add note to provider" (Heb: הוסף הערה לספק)

**Comment by samat89** [comment]
Changeset 2249
file Modules/Order/Templates/YTourServices/HotelService/HotelRoomServicePanel.html (lines: 141, 148, replaced strings accordingly)
