### ISSUE TITLE
Packages search -> package without car -> wrong details display

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#52]
Repro steps:

1) Search for packages without cat
2) Click button "serviceButtonDisplay"
![1](https://cloud.githubusercontent.com/assets/8789505/4304896/be4d6abe-3e74-11e4-9bbd-02949fe1699e.PNG)

Problem:
1) Details for car show (search for package without car)
2) "3 Intermediate stops" shown for flight without intermediate stops

**Comment by AlexSin15** [comment]
Changeset 2299
