### ISSUE TITLE
PopUp - Adding file to order

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#55]
![adding-file-to-order](https://cloud.githubusercontent.com/assets/8790191/4305719/6380d90c-3e7b-11e4-9664-ab0df00cc41a.jpg)

**Comment by feigale** [comment]
![popup additing file](https://cloud.githubusercontent.com/assets/8790628/4319455/a47b016a-3f2c-11e4-9ecc-879ff6c5ff07.jpg)
