### ISSUE TITLE
PopUp - Booking association to business customer

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#56]
![booking-association-to-business-customer](https://cloud.githubusercontent.com/assets/8790191/4305747/81ff9c6a-3e7b-11e4-96c4-e50a256df8c1.jpg)

**Comment by feigale** [comment]
Подогнать под дизайн - ширина PopUp не должна превышать 960 пикс.

**Comment by AlexSin15** [comment]
Changeset 2351
