### ISSUE TITLE
"New Search" tab's label not translated on language switch

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#57]
Repro steps:

1) Click on the "+"
2) Change language

Problem: tab's caption not translated

![1](https://cloud.githubusercontent.com/assets/8789505/4305725/6ceb6c28-3e7b-11e4-84cf-2e6a55a59d9e.PNG)

**Comment by DamirHaibullin** [comment]
Changeset 2269 - correction translate "new's search tabs" in Search.
Changeset 2270 - correction translate "new's search tabs" in Order tabs.
Changeset 2315 - change filter to directive i18n because become more message in console "Localization key not found in dictionary: 26-30/10/14.. "

**Comment by suhrab** [comment]
![image](https://cloud.githubusercontent.com/assets/4409852/4416229/0734c4c4-453d-11e4-910d-fccf10be8c32.png)

Values that are marked with red bullets in console should not go through localization module
