### ISSUE TITLE
PopUp - CD/DC

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#58]
![cd-dc](https://cloud.githubusercontent.com/assets/8790191/4305754/93bc7c48-3e7b-11e4-9659-269e42b14163.jpg)

**Comment by feigale** [comment]
![popupcd_dc](https://cloud.githubusercontent.com/assets/8790628/4319365/8dcb53d0-3f2b-11e4-9f23-db0693bd91f9.jpg)
