### ISSUE TITLE
PopUP - Voucher

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#59]
![voucher-4](https://cloud.githubusercontent.com/assets/8790191/4305768/a76b9bde-3e7b-11e4-9e1e-5b43065f33b1.jpg)
![voucher-2](https://cloud.githubusercontent.com/assets/8790191/4305766/a767d698-3e7b-11e4-9e7e-6f741b02b89c.jpg)
![voucher-6](https://cloud.githubusercontent.com/assets/8790191/4305767/a76ac5ba-3e7b-11e4-84db-226c6f7140e1.jpg)
![voucher-3](https://cloud.githubusercontent.com/assets/8790191/4305764/a7644ce4-3e7b-11e4-9409-182b5f1e16aa.jpg)
![voucher-1](https://cloud.githubusercontent.com/assets/8790191/4305765/a76587e4-3e7b-11e4-984f-64ac9a51bafc.jpg)
![voucher-5](https://cloud.githubusercontent.com/assets/8790191/4305769/a78c27aa-3e7b-11e4-95f7-2bd2c6758f8d.jpg)

**Comment by feigale** [comment]
![v1](https://cloud.githubusercontent.com/assets/8790628/4352677/c148fd20-4228-11e4-9fb5-52fdc78734a5.jpg)
![v2](https://cloud.githubusercontent.com/assets/8790628/4352679/c15f9a76-4228-11e4-9a2d-1c249e151509.jpg)
![v3](https://cloud.githubusercontent.com/assets/8790628/4352678/c15d86a0-4228-11e4-86cf-cc6bdd75a762.jpg)
![v4](https://cloud.githubusercontent.com/assets/8790628/4352680/c163acb0-4228-11e4-952d-966901f38412.jpg)
![v5](https://cloud.githubusercontent.com/assets/8790628/4352682/c167744e-4228-11e4-8837-5008e63fa62b.jpg)
![v6](https://cloud.githubusercontent.com/assets/8790628/4352681/c1657054-4228-11e4-8cd3-675a787119c4.jpg)
