### ISSUE TITLE
Promoted deal view - make hotel name bold & fix text truncating

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#61]
Repro steps:

1) Search for hotels
2) Click "boxIconGrey" button

![1](https://cloud.githubusercontent.com/assets/8789505/4316367/d9b369fc-3f05-11e4-940d-a42f7ddf79fe.PNG)

Problem(s):
1) The hotel name truncated to short (16 characters) - there is room for more characters. 
2) (fix) Make hotel name bold
3) Sometimes provider's name is in yellow - change this yellow color (not in screenshot)

**Comment by DamirHaibullin** [comment]
Changeset 2266 - change provider color 'yellow' to 'violet'
Changeset 2265 - change size hotel name from 16 to 22 characters and change bold by hotel name.
