### ISSUE TITLE
Promoted deal view - 2 popups in the same time

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#62]
Repro steps:

1) Do the search, Click the "BoxIconBlock" button
2) Click the "comments"  icon
3) Click the "gem" icon

![1](https://cloud.githubusercontent.com/assets/8789505/4316591/c4b9cce6-3f08-11e4-84ee-8c3ffa03da5c.PNG)

The problem:
There are 2 popups, one behind the other. 
The same thing gonna happen if you click first the "gem" icon, then the "comments".
The same thing on the grid view below promoted deals 
Only one popup among should be active

![2](https://cloud.githubusercontent.com/assets/8789505/4316611/1716c70a-3f09-11e4-83fd-3f2096d4e76e.PNG)

**Comment by DamirHaibullin** [comment]
Changeset 2262 - correction showing popups in HotelServiceBox.html.

**Comment by DamirHaibullin** [comment]
Changeset 2292 - change behavior by popup's.

**Comment by DamirHaibullin** [comment]
Changeset 2337 - if other box open popup not closing other popup another box.

**Comment by YairChen** [comment]
Did you check that you still give the ability to open second popup from opened popup? e.g. popup voucher which can be opened from provider accounting info popup. Please check it.

**Comment by DamirHaibullin** [comment]
I have checked. Popup in provider accounting work fine. Second popup can open from fist popup.
