### ISSUE TITLE
Hotels search -> "New search tab"  - "start date" is today

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#63]
Repro steps:

1) Do hotels search from 05/10/2014 until 11/10/2014 (6 nights)
2) Click on "+" tab
![1](https://cloud.githubusercontent.com/assets/8789505/4318657/aa5b672e-3f21-11e4-8de9-8e50a385bdda.PNG)
3) Click on "New Search" tab
![2](https://cloud.githubusercontent.com/assets/8789505/4318679/03238134-3f22-11e4-932a-bc8cd165e508.PNG)

Problem:
Start date is set to be today, should be taken from the previous tab.
Also, as a result number of nights is wrong

4) Press search button

![3](https://cloud.githubusercontent.com/assets/8789505/4318739/a5d2f018-3f22-11e4-8e94-0a8c4b96ab43.PNG)

Problem:
Label of the tab not matches to the dates in the filter

**Comment by samat89** [comment]
Changeset 2305
date-range-directive.js(26), ServiceSearchCtrl(516)
During initialization agent search(when we add new tab, pushing button "plus"), new tab gets data for date range from previous tab.
There was a problem in initialization new agent search, it is solved in directive date-range
