### ISSUE TITLE
Hotels search -> New search tab -> search results in other tab

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#64]
Repro steps:

1) Do hotel search
2) Click on "+" tab
3) Click on search icon

Problem:
Results are shown in the first tab, while the second (new own) is visually active
You can see the "progress" icon on the first tab "working"...

Results should go to the visually active tab

Hint: 
If you click upon "New Search" tab BEFORE clicking on search icon, everything works OK.

![1](https://cloud.githubusercontent.com/assets/8789505/4319462/b43c0a40-3f2c-11e4-80bf-29a946b7f8d1.PNG)

**Comment by samat89** [comment]
Changeset 2307

ServiceSearchCtrl.js(520).
At the time of adding the button "plus", added tab becomes active, also agent search is properly changed to active tab data.
