### ISSUE TITLE
PopUp - Accounting information corrections

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#65]
![accounting-information-01](https://cloud.githubusercontent.com/assets/8790191/4319521/76b9ef2e-3f2d-11e4-8c67-82c0e2bc6d14.jpg)
![accounting-information-02](https://cloud.githubusercontent.com/assets/8790191/4319520/76b2be20-3f2d-11e4-9bb2-a91147e1a767.jpg)
![accounting-information-03](https://cloud.githubusercontent.com/assets/8790191/4319518/76af5d84-3f2d-11e4-9403-2e5063071820.jpg)
![accounting-information-04](https://cloud.githubusercontent.com/assets/8790191/4319519/76b273b6-3f2d-11e4-9685-7dcfff37f295.jpg)

**Comment by feigale** [comment]
![accounting-information-01](https://cloud.githubusercontent.com/assets/8790628/4333543/d8e4d4ac-3fe1-11e4-9c47-d136ade9ecb3.jpg)
![accounting-information-02](https://cloud.githubusercontent.com/assets/8790628/4333544/d8e9f1d0-3fe1-11e4-9e02-17d025ac8e98.jpg)
![accounting-information-03](https://cloud.githubusercontent.com/assets/8790628/4333545/d8ecc090-3fe1-11e4-8618-88228a1940f0.jpg)
![accounting-information-04](https://cloud.githubusercontent.com/assets/8790628/4333546/d8f0fcc8-3fe1-11e4-9086-812e199b7ff0.jpg)
