### ISSUE TITLE
Hotels search -> "New search tabs"  - too many tabs

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#66]
You can open up to 3 "New search tabs" in "hotel search". When 3 tabs are opened, the "+"
button disabled.

![1](https://cloud.githubusercontent.com/assets/8789505/4319526/8c5deba0-3f2d-11e4-9c37-7f720e804ac0.PNG)

Problem: on the "Order" page "+" button still present, you can add more then 3 tabs...

![2](https://cloud.githubusercontent.com/assets/8789505/4319547/fcbf94a2-3f2d-11e4-9690-239f1de4e711.PNG)

Repro steps:

1) Do the hotels search
2) Add 2 more tabs, until "+" disappear
3) Add hotel to order and follow the arrow to the "Order" page

Problem: "+" button is there.

**Comment by novice3030** [comment]
fixed by me
