### ISSUE TITLE
PopUp Recept

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#70]
![recept-01](https://cloud.githubusercontent.com/assets/8790191/4347507/7f9576b4-4157-11e4-8100-8e60c71aad5f.jpg)
![recept-02](https://cloud.githubusercontent.com/assets/8790191/4347508/7f9a68d6-4157-11e4-859d-c132f58790c0.jpg)

**Comment by feigale** [comment]
![1](https://cloud.githubusercontent.com/assets/8790628/4352321/6ed9bb70-4222-11e4-87d2-6ca0242bb44f.jpg)
![2](https://cloud.githubusercontent.com/assets/8790628/4352320/6ed9a6e4-4222-11e4-9fa8-8551e9db55d4.jpg)
