### ISSUE TITLE
Z-Validate - locate in wrong place

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#71]
The Z-validate warning  for the client's name in service are located out of the textbox.
![3](https://cloud.githubusercontent.com/assets/7251658/4347682/081f1e8a-4163-11e4-8ee4-764ea72d545a.png)

**Comment by rem4ik4ever** [comment]
Please describe steps for getting that issue, because I don't have them in latest.

**Comment by rem4ik4ever** [comment]
Fixed that one. This is not z-validate issue this is more of markup issue, dut to element positioning with 'float: right' all inputs are stacked on right but z-validate is placed near to input, but has no float class.

**Comment by rem4ik4ever** [comment]
![zvalidate](https://cloud.githubusercontent.com/assets/3874496/4352065/8d512724-421c-11e4-9a87-9035383c65c0.PNG)

**Comment by novice3030** [comment]
i have fixed the issue with dynamic agency validation
it seems to be ok i will let @YairChen  and @Avi888 go over it and close the issue
