### ISSUE TITLE
Search again from existing service (After the first search failed) - stuck

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#76]
Search again from existing service (After the first search failed) - stuck
1. Add hotel service from the search to a new order
![21](https://cloud.githubusercontent.com/assets/7251658/4360544/cdee5576-427c-11e4-875b-de2d5f27c942.JPG)
1. copy the existing room
   ![23](https://cloud.githubusercontent.com/assets/7251658/4360423/c19741e4-427b-11e4-905b-86174a08a39c.JPG)
2. change the capacity of the second room and press the "dirty" button
   ![24](https://cloud.githubusercontent.com/assets/7251658/4360450/061e7828-427c-11e4-8b9a-0489860d520d.JPG)
3. In this example we need a search that no result match the request
   ![25](https://cloud.githubusercontent.com/assets/7251658/4360488/5b64b4be-427c-11e4-9169-5d91b6b120af.JPG)
4. After no results have been found, the "dirty" button changed to "search" button.
   Pressing on this button will stuck the system
   ![26](https://cloud.githubusercontent.com/assets/7251658/4360527/b6c41318-427c-11e4-8b30-24587a01ceb3.JPG)

**Comment by suhrab** [comment]
![image](https://cloud.githubusercontent.com/assets/4409852/4387391/1e0e12d4-43dc-11e4-8c35-1cfe6f1bcd34.png)

Got this error

**Comment by suhrab** [comment]
While was debugging this issue, found that either method **CheckHotleServiceAvailability** of BreezeApiController or **checkHotelServiceByParams** of OrderService.js can return several room results with same value of property **UnmappedRequestId**. For exampe it returned 2 rooms with UnmappedRequestId = "-16"

**Comment by suhrab** [comment]
Actually we dont need breeze tracking capabilities when checking room for availability:

``` javascript
var query = breeze.EntityQuery.from('CheckHotleServiceAvailability').withParameters({
            $method: 'POST',
            $encoding: 'JSON',
            $data: JSON.stringify(searchRequests)
        });
```

But turning off tracking with **.noTracking()** returns objects with **UnmappedRequestId** = undefined. Breeze bug?!

**Comment by suhrab** [comment]
Yes. It was a Breeze.js bug until 1.4.14. We use 1.4.11
Breeze team fixed it:

> D2579 - Fixed bug where the EntityQuery.noTracking option would not allow unmapped server props to go to the client from the server.

http://www.breezejs.com/documentation/release-notes

## Consider upgrading?

**Comment by suhrab** [comment]
Changeset 2328
