### ISSUE TITLE
customer popup is not centered correctly

### ISSUE THREAD

**Issue by novice3030** [yayasoft/ytour#82]
in customer popup we need to take in account the right div width that shows the current customers in order to center the window if it's visible.
this can be hard to do and we need to find the correct way to do it (we can't relay on the popup window width alone and the right div is not part of the popup)

![image](https://cloud.githubusercontent.com/assets/6697179/4371162/8714d0d4-4313-11e4-87b9-f38a3e121da5.png)

**Comment by YairChen** [comment]
more info:
Our customer use 1024X768 screen resolution. In this resolution, when you open this popup it not center correctly and the right side of the customer list view is partial shown

**Comment by web4social** [comment]
I fixed it, please check
