### ISSUE TITLE
PopUP - Adding Payment Methods

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#84]
![adding-payment-methods](https://cloud.githubusercontent.com/assets/8790191/4371216/7a65b12c-4314-11e4-9242-c3d4ad30dbc9.jpg)

**Comment by feigale** [comment]
![payment methods](https://cloud.githubusercontent.com/assets/8790628/4387712/0702963c-43e1-11e4-9e08-a06ea5c5d1f3.jpg)

**Comment by samat89** [comment]
Changeset 2382
AddPaymentController.js, OrderCtrl.js, AddPaymentPopup.html, CCPayments.css
Due to iframe can't be edited programmatically from another domain, third example image wasn't done.

**Comment by Avi888** [comment]
The design has not been repaired

![yt-05](https://cloud.githubusercontent.com/assets/8790191/4736090/f4248f20-59e8-11e4-8ddf-37ac97eba031.png)

**Comment by samat89** [comment]
Maybe, the cash should be cleared, because in my case it works properly.
