### ISSUE TITLE
Updating date range in second tab ("New Search") causes changes in the first tab.

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#85]
Repro steps:

1) Set date range in the first tab to 1/10 to 3/10
2) Open new tab
3) Change date range in the second tab to 1/11 to 3/11

Problem: in the first tab "to" date is set to 3/11. Tabs should "live independently"

**Comment by samat89** [comment]
Changeset 2327
ServiceSearchCtrl.js, date-range-directive.js, HotelsSearchView.html
Due to date-range-directive can't be applied for multitabbed system, used jquery to set ToDate value in HotelsSearchView.html

**Comment by novice3030** [comment]
why did you do  `<div id="dateRangeDiv" style="width: 205px;"> in HotelSearchView.html?`
you don't use it anywhere else please take it out (valid html must have a unique element id in angular if you find yourself giving an id to something you must be doing something wrong)

**Comment by samat89** [comment]
Ok, I will rewatch this issue.

**Comment by samat89** [comment]
Changeset 2374
Take out id div dateRangeDiv
