### ISSUE TITLE
Flight service - second customer has no seat details

### ISSUE THREAD

**Issue by YairChen** [yayasoft/ytour#86]
![41](https://cloud.githubusercontent.com/assets/7251658/4385371/ce1db602-43c3-11e4-9565-82022c8a6298.JPG)
![42](https://cloud.githubusercontent.com/assets/7251658/4385374/d377ac16-43c3-11e4-9b9c-733122d19b55.png)

**Comment by web4social** [comment]
resoleved Changeset 2330

**Comment by yosi-yaya** [comment]
not work

![1](https://cloud.githubusercontent.com/assets/8806064/4541628/cc5836e6-4e16-11e4-8d3c-950fc085d053.png)
