### ISSUE TITLE
first (after login) default search is wrong

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#87]
repro steps
1.isearch flight
2. log out
3. log in
4.i click button search

problem
default serach is "hotels" (in red color), but actual search is "flights" 
Seach result should match the selection 

![1](https://cloud.githubusercontent.com/assets/8806064/4385637/0475e442-43c7-11e4-8b64-8452b2762194.png)

**Comment by YairChen** [comment]
I add a another indication or problem to this issue:
Also without loging out, if you I was in flight search and then I  press on the order tab and then again I want to go to the flight search and press the search tab, the system always present the hotel as default even if I was in flight before I was switch to order tab.

**Comment by suhrab** [comment]
Changeset 2367 successfully checked in.
