### ISSUE TITLE
Additional flight passengers absent from order details

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#88]
Repro steps:

1)  Search for filghts
2   Click  "More passengers" link
3   In the pop up ad 1 child and one infant 
4   Search, and add to order any flight
5   Open order

Problem:
Infant and chile are absent from passengers list

![1](https://cloud.githubusercontent.com/assets/8806064/4385934/c10e0afa-43ca-11e4-8561-cbd4a51177b5.png)
![2](https://cloud.githubusercontent.com/assets/8806064/4385936/c42503d8-43ca-11e4-9b79-ac9e2b21e6df.PNG)

**Comment by web4social** [comment]
Yair said that the seat for infant is not necessary to add
resoleved Changeset 2330

**Comment by YairChen** [comment]
As far as I know, infant dosn't need a sit. they sit with their parents.

**Comment by yosi-yaya** [comment]
But he must go through a registration 
It also has an extra 40 nis I think 
Also if i adde child no add passenger line for child

**Comment by YairChen** [comment]
OK. Roman, make the changes needed to fix it.
