### ISSUE TITLE
no prices in result

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#93]
![1](https://cloud.githubusercontent.com/assets/8806064/4433540/131a65f6-46e0-11e4-8bb2-69ae7d9ba772.png)
![2](https://cloud.githubusercontent.com/assets/8806064/4433541/15100f28-46e0-11e4-80f9-47e26667fc1f.PNG)

**Comment by AlexSin15** [comment]
This is because rollback my changeset.
