### ISSUE TITLE
Changes in the characterization on hotels sum

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#94]
![sum-hotels-changes-in-the-characterization-02](https://cloud.githubusercontent.com/assets/8790191/4434511/008c2340-471a-11e4-949e-e1b134656a4b.jpg)
![sum-hotels-changes-in-the-characterization-01](https://cloud.githubusercontent.com/assets/8790191/4434510/00897050-471a-11e4-9681-db6ca46b3832.jpg)

**Comment by feigale** [comment]
![sum-hotels-changes-in-the-characterization-01](https://cloud.githubusercontent.com/assets/8790628/4439803/af81f526-47bc-11e4-9f8d-705411596972.jpg)
![sum-hotels-changes-in-the-characterization-02](https://cloud.githubusercontent.com/assets/8790628/4439802/af81536e-47bc-11e4-87eb-460807bc7926.jpg)

**Comment by Avi888** [comment]
OK
