### ISSUE TITLE
PopUp Business customer

### ISSUE THREAD

**Issue by Avi888** [yayasoft/ytour#95]
![business-customer-01](https://cloud.githubusercontent.com/assets/8790191/4438769/82015e5e-47b0-11e4-9cad-2ffba474dde6.jpg)
![business-customer-06](https://cloud.githubusercontent.com/assets/8790191/4438773/8212f79a-47b0-11e4-9eb3-c4d22dee0752.jpg)
![business-customer-02](https://cloud.githubusercontent.com/assets/8790191/4438770/820337d8-47b0-11e4-9449-4973b63a0a78.jpg)
![business-customer-04](https://cloud.githubusercontent.com/assets/8790191/4438772/820baeae-47b0-11e4-8aa4-cfd9f8537f3b.jpg)
![business-customer-05](https://cloud.githubusercontent.com/assets/8790191/4438771/8206c8ee-47b0-11e4-9db5-d816eb0368db.jpg)
![business-customer-03](https://cloud.githubusercontent.com/assets/8790191/4438775/822733d6-47b0-11e4-8fea-5f958caeebb8.jpg)
![business-customer-07](https://cloud.githubusercontent.com/assets/8790191/4438774/821fbd72-47b0-11e4-956f-8b268704f8c1.jpg)

**Comment by feigale** [comment]
![business-customer-01](https://cloud.githubusercontent.com/assets/8790628/4440165/abd8b518-47c1-11e4-9977-091e78bedf57.jpg)
![business-customer-02](https://cloud.githubusercontent.com/assets/8790628/4440166/abdaa382-47c1-11e4-8caa-08ced90f5d8f.jpg)
![business-customer-03](https://cloud.githubusercontent.com/assets/8790628/4440167/abdbcf14-47c1-11e4-9c1f-9ab96561c170.jpg)
![business-customer-04](https://cloud.githubusercontent.com/assets/8790628/4440168/abdeb2ce-47c1-11e4-89fe-7ddf9985b369.jpg)
![business-customer-05](https://cloud.githubusercontent.com/assets/8790628/4440169/abe01916-47c1-11e4-96e6-bcb8382e8123.jpg)
![business-customer-06](https://cloud.githubusercontent.com/assets/8790628/4440170/abfbeb6e-47c1-11e4-961e-9088c93fa406.jpg)
![business-customer-07](https://cloud.githubusercontent.com/assets/8790628/4440171/ac23b932-47c1-11e4-8c33-691b628ca3ff.jpg)

**Comment by AlexSin15** [comment]
Changeset 2420

**Comment by Avi888** [comment]
Nothing was repaired
