### ISSUE TITLE
Sorting results (Hotels/Flights/Packages)

### ISSUE THREAD

**Issue by simon-sh** [yayasoft/ytour#96]
Repro steps:

Do the search for hotels between the dates 26/10/2014 and 30/10/2014 (for instance)
Sort by price
Sort by A-B
Sort by start
Sort by price again…

Problem:
Selected sort is by price, highlighted in ping color, but results are NOT sorted by the price, probably sorted by several fields.

Expected:
Click upon on of the sort columns (price, A-B, or stars) will sort the results only by this single column, Each one of the sort options is completely independent of each other.
Also, icon 'arrow down' means from biggest to lowest

![1](https://cloud.githubusercontent.com/assets/8789505/4440840/9800d1c0-47ca-11e4-9a4b-d59d0ff239b7.PNG)

**Comment by AlexSin15** [comment]
Changeset 2353
