### ISSUE TITLE
Flight search - Select Multiple terminals got no results

### ISSUE THREAD

**Issue by yosi-yaya** [yayasoft/ytour#98]
1. I selected to departure from 2 airpot TLV + SDV and arrive to airport ETH at  2-5/10 , and I got NO results
2. if I selected to departure from 1 airport ETH ,and return from 2 airports TLV + SDV then I got result
   but only result with departure from ETH to TLV and not ETH to SDV
3. If I select only ETH to SDV then I got 92 results

**Comment by YairChen** [comment]
I rewrite the issue.

**Comment by suhrab** [comment]
Changeset 2355 successfully checked in.
